NHSDigital/nbs-appointments-management-service

- .gitignore
- azure-pipelines.yml
- src/client/package-lock.json
- src/client/package.json
- src/client/src/Components/ServiceSelector.test.tsx
- Add web client tests to pipeline
- Output results to tests tab in run overview using junit reporter
- Web client is published only if tests pass
- Web client published without unwanted files i.e. node_modules and test report
> APPT-37 Run web client tests in pipeline

- src/client/package-lock.json
- src/client/package.json
- Override nth-check to latest version that does not have the security vulnerability (2.1.1)
- Override postcss to latest version that does not have the security vulnerability (8.4.38)
> APPT-58 Resolve npm security vulnerabilities

- .gitignore
- .vscode/tasks.json
- README.md
- nbs-ams.code-workspace
- src/api/.vscode/tasks.json
- src/client/.gitignore
- src/client/.vscode/tasks.json
- src/new-client/.vscode/tasks.json
Creates a VS Code Workspace file as an entirely optional productivity tool for team members who wish to use VS Code. 
Includes tasks for: 
* Cleaning, building, then running the API functions
* Starting the docker services
* Building, testing and running the existing NextJS frontend
* Building, linting, formatting and running the new NextJS frontend we're about to start building. Naturally, running these tasks will fail until we've added this.
The workspace also includes a few local setting overrides, such as using prettier as the formatter for typescript files and enabling Format on Save.
> Create VS Code Workspace and helpful tasks

- nbs-ams.code-workspace
- src/new-client/.prettierrc
Configure both prettier and the VS Code workspace to use CRLF line endings, rather than LF.
> APPT - Ad Hoc - Formatter Line Endings

- src/new-client/src/app/home-page.test.tsx
- src/new-client/src/app/site/[site]/site-page.test.tsx
- src/new-client/src/app/site/[site]/users/manage/assign-roles-form.test.tsx
- src/new-client/src/app/site/[site]/users/manage/assign-roles.test.tsx
- src/new-client/src/app/site/[site]/users/manage/find-user-form.test.tsx
- src/new-client/src/app/site/[site]/users/users-page.test.tsx
- src/new-client/src/app/testing/render.ts
- src/new-client/tsconfig.json
The documentation for React Testing Library changed last year and now has a slightly different pattern for how you should invoke `userEvent`. It now wants you call a `setup()` method and obtain a `user` object, from which the type/click etc. methods can be called. 
To make this change more seamless, I've created a wrapper around the `render` method which calls `setup()` for us and allows us to destructure `user` for future use. 
For the mentioned change of usage please see:
https://testing-library.com/docs/user-event/intro
https://testing-library.com/docs/user-event/setup
> APPT-XXXX: Update usage of userEvent according to latest docs

- azure-pipelines.yml
- Explicitly lists dev variable group for dev deploy stage to prevent the auth values being overwritten by the EXP variable group which was added as part of the user testing deployment.
> Add dev variable group to dev stage

- src/new-client/src/app/lib/components/nhsuk-frontend/button-group.test.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/button-group.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/button.test.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/button.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/checkbox.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/checkboxes.test.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/checkboxes.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/fieldset.test.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/fieldset.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/form-group.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/index.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/select.test.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/select.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/text-area.test.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/text-area.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/text-input.test.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/text-input.tsx
- src/new-client/src/app/site/[site]/users/manage/assign-roles-form.test.tsx
- src/new-client/src/app/site/[site]/users/manage/assign-roles-form.tsx
- src/new-client/src/app/site/[site]/users/manage/find-user-form.test.tsx
- src/new-client/src/app/site/[site]/users/manage/find-user-form.tsx
* Creates a raft of nhs-uk styled form components.
* Establishes a pattern for using them with RHF by passing down the `ref` component using React's `forwardRef` feature. 
* Re-factors the Assign Roles Form and Find User Form to use this new pattern
> APPT-166: React Hook Form and NHS UK Frontend component pattern

- src/new-client/src/app/not-found.tsx
- src/new-client/testing/not-found.spec.ts
- src/new-client/testing/page-objects/not-found.ts
NextJS automatically creates a 404 page to serve up for invalid routes
By creating a file called `not-found` within the `app` folder, we can style this to our liking. 
Future PRs -> consider throwing the `notFound()` method from `client.ts` if we receive a 404 from the backend to instantly invoke this page. Also ask Thomas et al for what the text on this page should be
Old page: 
New page:
> Create Not Found page

- src/new-client/src/app/global.css
- src/new-client/src/app/lib/components/log-in-button.tsx
- src/new-client/src/app/lib/components/nhs-header-log-in.tsx
- src/new-client/src/app/lib/components/nhs-header-log-out.tsx
- src/new-client/src/app/lib/components/nhs-header.tsx
- src/new-client/src/app/lib/components/nhs-page.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/breadcrumbs.test.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/breadcrumbs.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/footer.test.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/footer.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/header.tsx
- src/new-client/src/app/lib/components/nhsuk-frontend/index.tsx
- src/new-client/src/app/site/[site]/page.tsx
- src/new-client/src/app/site/[site]/users/manage/page.tsx
- src/new-client/src/app/site/[site]/users/page.tsx
- src/new-client/testing/log-in.spec.ts
- src/new-client/testing/not-found.spec.ts
- src/new-client/testing/page-objects/root.ts
- src/new-client/testing/user-management-permissions.spec.ts
PR for tickets
1. [191](https://nhsd-jira.digital.nhs.uk/browse/APPT-191)
2. [192](https://nhsd-jira.digital.nhs.uk/browse/APPT-192)
3. [193](https://nhsd-jira.digital.nhs.uk/browse/APPT-193)
4. [194](https://nhsd-jira.digital.nhs.uk/browse/APPT-194)
5. [195](https://nhsd-jira.digital.nhs.uk/browse/APPT-195)
The breadcrumbs now properly render in mobile view (turns out it was just a typo in the classname `crumbs` vs `crumb` :D 
The login page design has been updated to include a button
The Home breadcrumb no longer appears on the login page
The root CSS styling has been updated - responsive views now have horizontal padding (actually turns out it was our custom styles which were breaking that previously, so I've re-jigged them)
Breadcrumb back links render in mobile view
An NHS footer has …
> Appt 191 192 193 195/UI cleanup

- infrastructure/environments/dev/main.tf
There is a bug with azurerm plugin version 4.1.0 which caused the plugin to crash. This has been raised and fixed by Hashicorp (https://github.com/hashicorp/terraform-provider-azurerm/issues/27301) just awaiting a release. So pinning version to last known working version of plugin until this is resolved.
> Pin terraform azurerm version to last known working version

- src/new-client/src/app/site/[site]/create-availability/page.tsx
- src/new-client/src/app/site/[site]/site-page.test.tsx
- src/new-client/src/app/site/[site]/site-page.tsx
- src/new-client/testing/create-availability.spec.ts
- src/new-client/testing/page-objects/create-availability.ts
- src/new-client/testing/page-objects/site.ts
Creates a "Create Availability" card on the site landing page. Permission checking for this card is out of scope for this ticket, being covered instead in APPT-62.
> APPT-242: Add create availability card and tests

- src/new-client/src/app/site/[site]/users/remove/page.tsx
- src/new-client/testing/create-and-remove-user.spec.ts
- src/new-client/testing/page-objects/user-management.ts
We're not pre-validating the search parameter in the remove-user confirmation route, but we've been asked to yield a 404 page in this scenario.
> APPT-313: Yield not found page when removing invalid user

- src/api/Nhs.Appointments.Api/Validators/SessionValidator.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/SessionValidatorTests.cs
- Add rule to prevent negative numbers being sent for capacity and slot length in the session object
- Updated unit tests
> APPT-324 - Validation for negative numbers for slot length and capacity

- src/new-client/.npmrc
- src/new-client/package-lock.json
- src/new-client/package.json
We don't currently enforce any particular version of node or npm during build. 
This PR pins us to npm >= 10 and node >= 20, and sets engine-strict to true which will fail the build if these requirements aren't met. 
It also forces peer, dev, and optional dependencies to be included on install in case local settings are set differently.
> Enforce npm and node version on install

- src/new-client/src/app/site/[site]/details/edit-information-for-citizens/information-for-citizens-page.test.tsx
I noticed one of our UI tests is causing console errors because of the use of a < text > element. It's only a mock element so it's now a span instead.
> Remove <text> tag which was triggering errors

- src/api/Nhs.Appointments.Api/Functions/ConfirmProvisionalBookingFunction.cs
- src/api/Nhs.Appointments.Core/BookingsService.cs
- src/api/Nhs.Appointments.Core/IBookingsDocumentStore.cs
- src/api/Nhs.Appointments.Persistance/BookingCosmosDocumentStore.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/ConfirmBooking.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/ConfirmBookingFeatureSteps.cs
Some code was intended to go into the PR for provisional bookings but was missed. It tackles a few edge cases and makes the process more robust
> Reintroduce missing code from previous PR

- src/new-client/src/app/lib/components/nhsuk-frontend/text-area.tsx
- src/new-client/src/app/site/[site]/details/edit-information-for-citizens/add-information-for-citizens-form.tsx
- src/new-client/src/app/site/[site]/details/edit-information-for-citizens/add-information-for-citizens.test.tsx
- src/new-client/src/constants.tsx
- Adding a max length of 150 to the site information text area
- Including remaining character count beneath the text area
- Adding checks to see if the text contains certain special characters or a URL and if so, fail validation, don't allow for submission and display a validation message
> Appt 270 additional site info validation

- infrastructure/resources/api.tf
- mock-data/CosmosDbSeeder/items/index_data/notification_config.json
- src/api/Nhs.Appointments.Api/Consumers/BookingCancelledConsumer.cs
- src/api/Nhs.Appointments.Api/Functions/CancelBookingFunction.cs
- src/api/Nhs.Appointments.Api/Functions/NotifyBookingCancelledFunction.cs
- src/api/Nhs.Appointments.Api/Notifications/BookingNotifier.cs
- src/api/Nhs.Appointments.Api/Notifications/ConsoleLogNotifications.cs
- src/api/Nhs.Appointments.Api/Notifications/IBookingCancelledNotifier.cs
- src/api/Nhs.Appointments.Api/Notifications/ServiceRegistration.cs
- src/api/Nhs.Appointments.Api/Notifications/template-bookingcancelled-rsv-email.txt
- src/api/Nhs.Appointments.Api/Notifications/template-bookingcancelled-rsv-sms.txt
- src/api/Nhs.Appointments.Api/local.settings.json
- src/api/Nhs.Appointments.Core/BookingsService.cs
- src/api/Nhs.Appointments.Core/IBookingsDocumentStore.cs
- src/api/Nhs.Appointments.Core/Messaging/Events/BookingCancelled.cs
- tests/Nhs.Appointments.Api.UnitTests/Consumers/BookingCancelledConsumerTests.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/CancelBookingFunctionTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BookingServiceTests.cs
To enable cancellation notifications for the other service types (covid 19, flu etc):
- add the templates to Gov Notify 
- add the new template GUIDs to the notification_config item in Cosmos
- add the template text files to the solution for safekeeping
> RSV booking cancellation notifications

- src/new-client/src/app/lib/components/nhsuk-frontend/text-input.tsx
- src/new-client/src/app/lib/components/wizard.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/availability-template-wizard.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/days-of-week-step.test.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/days-of-week-step.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/select-services-step.test.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/select-services-step.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/single-or-repeating-session-step.test.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/single-or-repeating-session-step.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/start-and-end-date-step.test.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/start-and-end-date-step.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/summary-step.test.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.test.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.tsx
Contains a series of requested changes to the Create Availability Wizard. Namely: 
- APPT-406: If the user has previously reached the final step of the wizard, then clicked "Change" or "Go back" to visit and change a prior step, the `Continue` buttons on that step will now take them straight back to the summary screen rather than the next step.
- APPT-40?: If the user changes between Single Date Session and Weekly Repeating Session, the remaining form entries will be wiped clean and reset. 
- APPT-401: Inputs are now controlled as well as validated. Users can no longer enter whatever they want (i.e. no minuses, no text, etc.). This was always being validated but now is being enforced on input change. 
- APPT-403: All default values have been removed. Users do not get anything …
> APPT-309: Create availability updates

- src/new-client/src/app/site/[site]/create-availability/wizard/capacity-calculation.test.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/capacity-calculation.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/summary-step.test.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/summary-step.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.test.tsx
- src/new-client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.tsx
Out of this morning's discussion:
- The words "Up to" have been prepended to the "appointments per hour" calculation in every case.
- The entire "appointments per hour" calculation is hidden if the total session length does not exceed 60 minutes
- The copy for "Vaccinators or spaces" is now "Vaccinators or vaccination spaces"
> APPT-239: Capacity calculation tweaks

- mock-data/CosmosDbSeeder/items/booking_data/availability_created_ABC02_20200101145431233324.json
- src/api/Nhs.Appointments.Api/Functions/GetAvailabilityCreatedEventsFunction.cs
- src/api/Nhs.Appointments.Api/Models/GetAvailabilityCreatedEventsRequest.cs
- src/api/Nhs.Appointments.Api/Validators/GetAvailabilityCreatedEventsRequestValidator.cs
- src/api/Nhs.Appointments.Core/AvailabilityService.cs
- src/api/Nhs.Appointments.Core/IAvailabilityService.cs
- src/new-client/src/app/lib/services/appointmentsService.ts
- tests/Nhs.Appointments.Api.Integration/Scenarios/CreateAvailability/GetAvailabilityCreatedEventsFeatureSteps.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/GetAvailabilityCreatedEventsFunctionTests.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/GetAvailabilityCreatedEventsRequestValidatorTests.cs
- tests/Nhs.Appointments.Core.UnitTests/AvailabilityServiceTests.cs
Satisfies two more acceptance criteria of the Create Availability page: 
- Created availability should be ordered by date ascending. For templates, this ordering should be done on FROM first then on TO in the case of a tie. 
- If ALL dates within a period described by an Availability Created Event are in the past, that entry should not appear in the table
> APPT-368: Ordering and filtering of Availability Created Events

- src/api/Nhs.Appointments.Api/Functions/MakeBookingFunction.cs
- src/api/Nhs.Appointments.Core/Metrics/InMemoryMetricsRecorder.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/MakeBooking.feature
- tests/Nhs.Appointments.Api.UnitTests/Functions/MakeBookingFunctionTests.cs
Checks for site when processing a booking request and sends a specific error message if the site does not exist
Also fixed some thread / concurrency issues with the metrics recorder as they were causing integration test failures
> Fix for site not found when booking

- src/client/src/app/site/[site]/create-availability/wizard/capacity-calculation.test.tsx
- src/client/src/app/site/[site]/create-availability/wizard/capacity-calculation.tsx
As discussed in sprint planning yesterday, session calculations will now round DOWN whilst hour calculations will round UP. 
Unit tests have been expanded to cover the cases discussed in numerous bunkers.
> APPT-239: Changes requested to capacity calculation

- postman-collection/Appointment Service.postman_collection.json
- src/api/Nhs.Appointments.Api/Functions/GetDailyAvailabilityFunction.cs
- src/api/Nhs.Appointments.Api/Models/GetDailyAvailabilityRequest.cs
- src/api/Nhs.Appointments.Api/Validators/GetDailyAvailabilityRequestValidator.cs
- src/api/Nhs.Appointments.Core/AvailabilityService.cs
- src/api/Nhs.Appointments.Core/DailyAvailability.cs
- src/api/Nhs.Appointments.Core/IAvailabilityService.cs
- src/api/Nhs.Appointments.Core/IAvailabilityStore.cs
- src/api/Nhs.Appointments.Persistance/AvailabilityDocumentStore.cs
- src/api/Nhs.Appointments.Persistance/CosmosAutoMapperProfile.cs
- src/client/src/app/lib/services/appointmentsService.ts
- src/client/src/app/lib/services/timeService.ts
- src/client/src/app/lib/types/index.tsx
- src/client/src/app/site/[site]/view-availability/view-availability-page.tsx
- src/client/src/app/site/[site]/view-availability/week/page.tsx
- src/client/src/app/site/[site]/view-availability/week/view-week-availability-page.test.tsx
- src/client/src/app/site/[site]/view-availability/week/view-week-availability-page.tsx
- src/client/src/app/testing/data.ts
- tests/Nhs.Appointments.Api.Integration/Nhs.Appointments.Api.Integration.csproj
- tests/Nhs.Appointments.Api.Integration/Scenarios/Availability/DailyAvailability.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/Availability/DailyAvailabilityFeatureSteps.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/GetDailyAvailabilityFunctionTests.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/GetDailyAvailabilityRequestValidatorTests.cs
- tests/Nhs.Appointments.Core.UnitTests/AvailabilityServiceTests.cs
This is PART 1 of multiple pull requests for APPT-338. This part includes
- New GET daily-availability endpoint which returns the daily availability document in a list for each day between the date range requested
- Unit tests and integration tests for the new endpoint
- Front end changes that are hooked up to this endpoint (no booking / unbooked calculations so far, merely hooking this up on the front end)
- Front end unit tests
- Front end TODOs
> Appt 338/get daily availability endpoint - PART 1

- src/api/Nhs.Appointments.Core/BookingsService.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/QueryBookingByNhsNumber.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/SystemFunctions/RunReminders.feature
Will not send a reminder if a booking was made less than 24 hours ago (includes rescheduled bookings)
> prevent sending reminders for recently booked appointments

- src/client/testing/eula.spec.ts
- tests/Nhs.Appointments.Api.Integration/Scenarios/Eula/ConsentToEula.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/SystemFunctions/RunReminders.feature
Tests are skipped temporarily until investigated and fixed
> Skip flaky integration tests to stabilise build

- docker-compose.yml
- infrastructure/resources/api.tf
- infrastructure/resources/web.tf
- src/api/Nhs.Appointments.Api/local.settings.json
- src/client/.env
- src/client/next.config.mjs
- src/client/src/app/auth/set-cookie/route.ts
- src/client/src/app/global.css
- src/client/src/app/home-page.test.tsx
- src/client/src/app/lib/components/site-list.test.tsx
- src/client/src/app/lib/components/site-list.tsx
- src/client/src/app/lib/services/appointmentsService.ts
- src/client/src/app/site/[site]/site-page.test.tsx
- src/client/src/app/site/[site]/site-page.tsx
- src/client/testing/create-and-remove-user.spec.ts
- src/client/testing/eula.spec.ts
- src/client/testing/page-objects/root.ts
- src/client/testing/playwright.env
- src/client/testing/user-management-permissions.spec.ts
Prepends `/manage-your-appointments` to all client routes, using NextJS' [basePath ](https://nextjs.org/docs/app/api-reference/config/next-config-js/basePath) configuration property. 
Frustratingly, this works within components whilst using [Link](https://nextjs.org/docs/pages/api-reference/components/link), or within server actions when invoking redirect, but NOT when invoking redirect from a route handler. This has been raised as an [open issue](https://github.com/vercel/next.js/issues/56229) several times on Vercel's github page, e.g. 
To get around this, I've introduced the basePath as an environment variable and manually prepended it to URLs derived during the `set-cookie` route handler. As this is our only route handler for now, it's tech debt I'm willing (but grumpy) to incur.
> Appt-XXX: Introduce client basePath

- src/client/src/app/lib/components/nhs-page.tsx
Some pages recently had their breadcrumbs removed, but didn't have the `omitTitleFromBreadcrumbs` argument added. Hence the page title has still been appearing as a sole breadcrumb. 
Since it's a bit unclear from the tickets/designs exactly which pages should have breadcrumbs, I'm not reviewing them all here. This PR simply adds in an extra condition to the automatic title addition so it won't add to the title to the empty array.
> APPT-XXX: Fix title being appended to empty breadcrumb trails

- src/client/src/app/lib/components/nhsuk-frontend/index.tsx
- src/client/src/app/lib/components/nhsuk-frontend/pagination.tsx
- src/client/src/app/lib/components/nhsuk-frontend/tabs.test.tsx
- src/client/src/app/lib/components/nhsuk-frontend/tabs.tsx
- src/client/src/app/site/[site]/view-availability/daily-appointments/daily-appointments-page.test.tsx
- src/client/src/app/site/[site]/view-availability/daily-appointments/daily-appointments-page.tsx
- src/client/src/app/site/[site]/view-availability/daily-appointments/page.tsx
- Resolves console errors that `tabs.test.tsx` was causing
- Moves the logic for handling tab selection into the Tabs component so the consumer doesn't have to implement it themselves
- Refactors the tabs/pagination on these pages to avoid unnecessary server round-trips
> Avoid unnecessary server trips when using tabs and pagination

- data/CosmosDbSeeder/items/stag/core_data/notification_config.json
Dummy config added for covid and flu cancellation notifications to support perf testing whilst real templates do not exist
> Add dummy notification cancelled config for covid and flu

- src/api/Nhs.Appointments.Api/Functions/QueryBookingByReferenceFunction.cs
- src/api/Nhs.Appointments.Api/Models/QueryBookingByReferenceRequest.cs
- src/client/src/app/lib/services/appointmentsService.ts
- src/client/src/app/site/[site]/appointment/[reference]/cancel/page.tsx
- tests/Nhs.Appointments.Api.UnitTests/Functions/QueryBookingByReferenceNumberTests.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/QueryBookingByReferenceRequestValidatorTests.cs
Adding an optional site query string to the GetBookingByReferenceNumber endpoint so we can access it from the front end without having the booking:query permission set globally.
> APPT-146 - Get booking by reference number endpoint update

- src/client/src/app/site/[site]/users/users-page.tsx
I noticed the table styling is off for rows without the Manage/Remove actions. This is because we're rendering null rather than empty `<td>` elements. This PR passes two empty strings instead so the table still renders `<td>` elements with their border styling.
> Tiny styling bug fix

- .gitignore
Add the data import markdown reports to .gitignore so they don't appear as changes after running the DB seeder
> Add data import reports to git ignore

- src/api/Nhs.Appointments.Core/AvailabilityCalculator.cs
- src/api/Nhs.Appointments.Core/AvailabilityService.cs
- src/api/Nhs.Appointments.Core/Booking.cs
- src/api/Nhs.Appointments.Core/BookingsService.cs
- src/api/Nhs.Appointments.Core/ScheduleTemplate.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/BookingBaseFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/Cancel.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/CancelFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/CreateAvailability/ApplyAvailabilityTemplate.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/CreateAvailability/SetAvailability.feature
- tests/Nhs.Appointments.Core.UnitTests/AvailabilityServiceTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BookingsServiceTests.cs
- Introduces the concept of "Orphaned" appointments and extends the `AppointmentStatus` enum
- Creates a method for programmatically re-assessing the status of every appointment for a given day, adopting any orphans if possible and orphaning any scheduled appointments if needed.
- Calls this method after single day availability is created, availability templates are applied, or appointments are cancelled. 
- Adds tests for all the above
> APPT-509: Introduce Orphaned appointment status and recalculate when availability changes

- src/client/package-lock.json
- src/client/package.json
NextJS is warning us of a vulnerability in 14.2.20 and recommends upgrading to the latest version within major v14.
> APPT-XXX: Upgrade nextjs to address vulnerability

- src/api/Nhs.Appointments.Core/BookingsService.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/CreateAvailability/ApplyAvailabilityTemplate.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/CreateAvailability/SetAvailability.feature
The availability re-calculator currently uses the definition of a `Live Booking` to generate the list of bookings to operate over.
It does this because Provisional bookings still consume availability, however due to an oversight it was flipping Provisional bookings from Provisional -> Booked when it determined that they still had supporting availability. 
This PR fixes that bug, and adds in tests to cover this case. It also covers some extra cases, such as Cancelled appointments and date Created by ordering.
> APPT-364: Prevent the availability re-calculator from flipping supported provisional bookings

- src/client/src/app/lib/components/nhsuk-frontend/back-link.tsx
- src/client/src/app/site/[site]/create-availability/wizard/availability-template-wizard.tsx
- src/client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.test.tsx
- src/client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.tsx
I had intended to do this properly, but time constraints being what they are this is a temporary hacky measure to meet the requirement. 
If a user has clicked on "Add Session" from the Week View availability page, they will be jumped straight into the wizard at step 4 (since we already have all the information steps 1-3 gather). When they click "Go Back", rather than actually navigate the wizard they want this to return them to the Week View page. 
I will do this properly in the fullness of time by creating a separate wizard with only steps 4 and 5 (since the summary screen is also not needed in this journey, but they haven't complained about that yet). This might be a post-beta change though!
> APPT-545: Return user to week view after Going Back from appropriate wizard step

- src/api/Nhs.Appointments.Api/Auth/AuthUtilities.cs
- src/api/Nhs.Appointments.Api/Functions/GetAuthTokenFunction.cs
Get email for auditing login from the id_token, but it could be in a different place due to different Id server configs. 
Add utility method for help trying to find it.
Throw InvalidOperationException if not found as may need further investigation.
TODO as tech debt
Tests
Structured logging?
> APPT-518 - Audit login user not generated consistently due to different ID server configuration

- src/api/Nhs.Appointments.Api/Functions/ConfirmProvisionalBookingFunction.cs
- src/api/Nhs.Appointments.Core/IBookingsDocumentStore.cs
- src/api/Nhs.Appointments.Persistance/BookingCosmosDocumentStore.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/ConfirmBooking.feature
The `ConfirmProvisionalBookingFunction` does not currently check that a booking is `Provisional` before proceeding to confirm it. 
This PR locks it down so it will return 412 if the booking status is anything other than `Provisional`.
> APPT-577: Return 412 when trying to confirm a booking which is not provisional

- src/client/src/app/lib/components/session-summary-table.tsx
- src/client/src/app/lib/services/availabilityCalculatorService.ts
- src/client/src/app/lib/types/index.tsx
- src/client/src/app/site/[site]/view-availability/week/day-summary-card.test.tsx
- src/client/src/app/site/[site]/view-availability/week/day-summary-card.tsx
- src/client/src/app/site/[site]/view-availability/week/view-week-availability-page.tsx
- src/client/src/app/testing/availability-and-bookings-mock-data.ts
- src/client/src/app/testing/data.ts
The cards on the Weekly Availability page currently only render a link to the Daily Availability page if there is availability on that day. However it's possible to have orphaned and cancelled bookings without availability (if availability is cancelled, for example). Therefore this page needs to still present the link. 
After further discussion with the content and design team, this view has been updated to match the below screenshot. This has required tracking orphaned and cancelled appointments throughout the availability calculations (where previously they were filtered out and the calculation was only ran on booked appointments).
> APPT-581: View daily appointments when there are bookings but no availability

- src/client/src/app/lib/components/nhs-page.tsx
Users should be able to see the _Change site details link_ if they have the `site:view` permission
> Updating permissions on change site details link

- src/client/src/app/site/[site]/availability/cancel/confirm-cancellation.test.tsx
- src/client/src/app/site/[site]/availability/cancel/confirm-cancellation.tsx
- src/client/src/app/site/[site]/view-availability/week/edit-session/edit-session-decision.test.tsx
- src/client/src/app/site/[site]/view-availability/week/edit-session/edit-session-decision.tsx
Ste and I forgot to add validation to this radio buttons for the Edit/Cancel Session routes
> APPT-589: Add validation to the cancel and edit session decision screens

- src/api/Nhs.Appointments.Core/BookingsService.cs
- tests/Nhs.Appointments.Core.UnitTests/BookingsServiceTests.cs
The Availability Re-calculator currently orphans Booked or Provisional appointments if there is no longer availability to fulfil them. 
This exposes a risk because the NBS journey for a patient involves creating them a Provisional booking, then confirming it as a Booked booking at the end of the UI flow. If this Provisional booking gets orphaned whilst the user is going through this journey, they'll be told the booking was unsuccessful but clinicians in MYA will see an Orphaned booking and might decide to "honour" it.
> APPT-587: Prevent Provisional appointments from being Orphaned

- src/client/src/app/eula/accept-eula-form.tsx
- src/client/src/app/eula/eula-page.test.tsx
- src/client/src/app/eula/page.tsx
- src/client/src/app/lib/services/appointmentsService.ts
- src/client/src/app/lib/services/viewAvailabilityService.test.ts
- src/client/src/app/lib/services/viewAvailabilityService.ts
- src/client/src/app/site/[site]/appointment/[reference]/cancel/cancel-appointment-page.tsx
- src/client/src/app/site/[site]/availability/cancel/confirm-cancellation.tsx
- src/client/src/app/site/[site]/availability/edit/edit-session-time-and-capacity-form.tsx
- src/client/src/app/site/[site]/create-availability/availabilityCreatedEventsTable.test.tsx
- src/client/src/app/site/[site]/create-availability/availabilityCreatedEventsTable.tsx
- src/client/src/app/site/[site]/create-availability/create-availability-page.test.tsx
- src/client/src/app/site/[site]/create-availability/create-availability-page.tsx
- src/client/src/app/site/[site]/users/remove/remove-user-page.tsx
- src/client/src/app/site/[site]/view-availability/page.tsx
- src/client/src/app/site/[site]/view-availability/view-availability-page.test.tsx
- src/client/src/app/site/[site]/view-availability/view-availability-page.tsx
- src/client/src/app/site/[site]/view-availability/week-card-list.test.tsx
- src/client/src/app/site/[site]/view-availability/week-card-list.tsx
- src/client/src/app/site/[site]/view-availability/week/edit-session/edit-session-decision.tsx
- src/client/src/app/site/[site]/view-availability/week/page.tsx
- src/client/src/app/site/[site]/view-availability/week/view-week-availability-page.test.tsx
- src/client/src/app/site/[site]/view-availability/week/view-week-availability-page.tsx
Components which take a long time to load currently block the entire rendering process. This isn't a problem yet, but once the monthly/weekly view availability pages start fetching thousands of appointments they could seem unresponsive to users with slower connections. 
This PR moves expensive API calls lower down the component tree and wraps them in [Suspense ](https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming) boundaries so the basic page load can happen, and only the components which depend on the slow data are blocking. A loading spinner is shown whilst these components load. 
I have tested these components locally by throttling my browser and adding manual delays to the backend API. I am trusting our e2e tests for a regression against existing …
> APPT-489: Wrap expensive components behind suspense boundaries

- src/client/src/app/lib/services/availabilityCalculatorService.ts
- src/client/src/app/site/[site]/appointment/[reference]/cancel/page.tsx
- src/client/src/app/site/[site]/availability/cancel/confirmed/page.tsx
- src/client/src/app/site/[site]/availability/cancel/page.tsx
- src/client/src/app/site/[site]/availability/edit/confirmed/page.tsx
- src/client/src/app/site/[site]/availability/edit/page.tsx
- src/client/src/app/site/[site]/create-availability/page.tsx
- src/client/src/app/site/[site]/create-availability/wizard/page.tsx
- src/client/src/app/site/[site]/details/edit-attributes/edit-attributes-page.tsx
- src/client/src/app/site/[site]/details/edit-attributes/page.tsx
- src/client/src/app/site/[site]/details/edit-information-for-citizens/page.tsx
- src/client/src/app/site/[site]/details/page.tsx
- src/client/src/app/site/[site]/details/site-details-page.tsx
- src/client/src/app/site/[site]/page.tsx
- src/client/src/app/site/[site]/users/manage/assign-roles.tsx
- src/client/src/app/site/[site]/users/manage/page.tsx
- src/client/src/app/site/[site]/users/page.tsx
- src/client/src/app/site/[site]/users/remove/page.tsx
- src/client/src/app/site/[site]/view-availability/daily-appointments/page.tsx
- src/client/src/app/site/[site]/view-availability/page.tsx
- src/client/src/app/site/[site]/view-availability/week/edit-session/page.tsx
- src/client/src/app/site/[site]/view-availability/week/page.tsx
Assert permission check (if exists) is always first call at top of page, and always awaited separately. All data needed to construct the page is wrapped in the Promise.All if more than one.
> Appt xxx/parallel fetching

- src/client/package-lock.json
- src/client/package.json
- src/client/src/app/login/page.tsx
- src/client/src/app/site/[site]/details/edit-attributes/page.tsx
- src/client/src/app/site/[site]/details/edit-information-for-citizens/page.tsx
A memory leak has been found in the NextJS web app server. We think this is caused by the [inflight](https://www.npmjs.com/package/inflight) package, which is a dependency of glob, which is a dependency of Jest's latest version. 
Later versions of glob have replaced this dangerous dependency, but [the latest version of Jest still uses the older versions of glob which include it](https://github.com/jestjs/jest/issues/15173#issuecomment-2338428790). Frustrating, this [still hasn't been fixed in the alpha version of jest@next](https://github.com/jestjs/jest/issues/15236). 
This PR overrides the glob version requested by jest with the later version which does not include the inflight package.
It also removes several linting errors that have been committed to main.
> APPT-603: Remove inflight package

- src/api/Nhs.Appointments.Api/Functions/GetSitesPreviewFunction.cs
- src/api/Nhs.Appointments.Core/Site.cs
- src/api/Nhs.Appointments.Core/SiteService.cs
- src/client/package-lock.json
- src/client/package.json
- src/client/src/app/lib/components/site-list.test.tsx
- src/client/src/app/lib/components/site-list.tsx
- src/client/src/app/lib/utils/debounce.ts
- src/client/testing/home.spec.ts
- tests/Nhs.Appointments.Api.UnitTests/Functions/GetSitesPreviewFunctionTests.cs
Search bar for filtering sites:
- Requires at least 3 characters to be input before filtering
- Case insensitive
- Will match on ODS _only_ if it matches **exactly**. 
- Exposing the ODS code on the _sites-preview_ endpoint so we can filter on it
- There were no designs on the ticket itself for the search input so I've gone with this by using the existing TextBox component
Out of scope for APPT-525 but the _sites-preview_ endpoint will return all sites a user has permission to without pagination or without limiting the number of sites returned at a given time. It might be worth considering if we need to add this in at some point in the future, either for MVP or post-MVP
> APPT-525 - Add site search functionality on the front end. 

- src/api/Nhs.Appointments.Persistance/BookingCosmosDocumentStore.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
Currently the cleanup process runs every 5 mins. This process deletes all provisional bookings that have been expired as of 5 mins ago. This creates an issue where, depending on when the initial booking was made, the 'expired' status of a provisional booking (5 mins old) only exists in the DB between 0-5 mins, before being hard-deleted. 
I have upped the cleanup expired time cleanup, so that now 'Expired' bookings (5 mins old) will exist in the DB for 10-15 more mins before being removed.
Tech Debt Future - We really should have any variables like this controlled via IOptionsMonitor and injected in via config, so we wouldn't have to make further code changes in future.
> APPT-343 - Expired booking cleanup bugfix

- src/api/Nhs.Appointments.Persistance/BookingCosmosDocumentStore.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
We don't need to be so aggressive with cleanup. NBS bookings can be on the page for an indeterminately long time, so might as well push the cleanup to cleanup daily.
Tech Debt: Ideally would be nice to have a heartbeat functionality where NBS slides our expiry time for a specific booking, if user is still on the NBS page. No time for that though yet!!
> APPT-634 Daily expired provisional cleanup

- src/client/src/app/login/log-in-button.tsx
- src/client/src/app/login/page.tsx
- src/client/src/middleware.ts
- src/client/testing/tests/create-availability/create-availability.spec.ts
The login buttons currently invoke server actions to redirect to the API auth functions. 
This is causing conflicts in Akamai, where NextJS believes these are internal routes (because of the subdomains) and tries to route them against its own router. 
This PR switches the server actions out to use simple client side redirection instead.
> APPT-XXX: Bypass server redirect for login

- src/client/testing/eula.spec.ts
I don't know why this was ever added, I think this test passes fine. Unless the pipeline is about to prove me wrong...
> APPT-XXX: Remove the fixme on the eula tests

- src/api/Nhs.Appointments.Api/Middleware/NoCacheMiddleware.cs
- src/api/Nhs.Appointments.Api/Program.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/NoCache/NoCache.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/NoCache/NoCacheSteps.cs
- tests/Nhs.Appointments.Api.UnitTests/Audit/FunctionMiddlewareTests.cs
A new middleware has been implemented to add multiple headers to HTTP responses. 
These headers are designed to prevent Akamai from caching API responses.
> APPT-655 - Added cache control headers

- data/CosmosDbSeeder/items/dev/core_data/notification_config.json
- data/CosmosDbSeeder/items/int/core_data/notification_config.json
- data/CosmosDbSeeder/items/local/core_data/notification_config.json
- src/api/Nhs.Appointments.Api/Consumers/OktaUserRolesChangedConsumer.cs
- src/api/Nhs.Appointments.Api/Consumers/UserRolesChangedConsumer.cs
- src/api/Nhs.Appointments.Api/Functions/NotifyOktaUserRolesChangedFunction.cs
- src/api/Nhs.Appointments.Api/Notifications/ConsoleLogNotifications.cs
- src/api/Nhs.Appointments.Api/Notifications/ServiceRegistration.cs
- src/api/Nhs.Appointments.Api/Notifications/UserRolesChangedNotifier.cs
- src/api/Nhs.Appointments.Core/Messaging/Events/OktaUserRolesChanged.cs
- src/api/Nhs.Appointments.Core/UserService.cs
- tests/Nhs.Appointments.Api.UnitTests/Consumers/OktaUserRolesChangedConsumerTests.cs
When calling the SetUserRolesFunction endpoint, we currently send out the "UserRolesChanged" event. We have introduced a new event, "OktaUserRolesChanged", specifically for Okta users. This ensures that Okta users receive a different email from NHS users.
> APPT-617 email notification for okta users

- docker-compose.yml
- infrastructure/resources/high_load_functions.tf
- infrastructure/resources/http_functions.tf
- infrastructure/resources/servicebus_functions.tf
- infrastructure/resources/timer_functions.tf
- src/api/Nhs.Appointments.Api/Functions/NotifyOktaUserRolesChangedFunction.cs
- src/api/Nhs.Appointments.Api/Notifications/ServiceRegistration.cs
- src/api/Nhs.Appointments.Api/local.settings.json
`NotifyOktaUserRolesChanged`, `SetSiteDetailsFunction`, and `SetSiteReferenceDetailsFunction` are currently enabled in all resources, including the high load functions which cost more. This PR disables `SetSiteDetailsFunction` and `SetSiteReferenceDetailsFunction` for all but http functions and `NotifyOktaUserRolesChanged` for all but the service bus functions.
Also fixes some bugs with the Okta user roles function, namely that it was using the wrong consumer and wasn't being registered.
Also disables the Okta notification function locally to prevent the following console errors:
> APPT-XXX: Disable functions and fix local errors

- src/api/Nhs.Appointments.Core/CsvProcessor.cs
- tests/Nhs.Appointments.Core.UnitTests/SiteDataImporterHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/UserDataImportHandlerTests.cs
The try catch is placed where it is because in some instances an exception is only thrown on the foreach (...) line e.g. when a mandatory column is missing.
> APPT-717 - Adding a try catch in the CSV processor and reporting it

- src/client/src/app/cookies-policy/page.tsx
Corrects some erroneous copy in the cookies policy page, as per the below different between actual and JIRA:
> APPT-597: Fix copy error on cookie policy page

- src/api/Nhs.Appointments.Api/Features/FeatureConfigurationExtensions.cs
- src/api/Nhs.Appointments.Api/Features/FeatureToggleHelper.cs
- src/api/Nhs.Appointments.Api/Features/LocalConfigurationRefresher.cs
- src/api/Nhs.Appointments.Api/Program.cs
- tests/Nhs.Appointments.Api.UnitTests/Features/FeatureToggleHelperTests.cs
The app has the ability to call the refresh when a feature toggle state is requested. Fire off without awaiting to avoid execution delay. Register local config refresher. Refactor all feature related registration into a single place.
> APPT-672 Add registration of IConfigurationRefresher.

- src/client/package-lock.json
- src/client/package.json
- src/client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.test.tsx
- src/client/src/app/site/[site]/users/manage/find-user-form.test.tsx
- src/client/src/app/site/[site]/users/manage/find-user-form.tsx
- src/client/src/constants.tsx
Tech debt item I've been wanting to get to for awhile, seems relevant now with Okta changes coming up.
Yup schema validation works really well with RHF because:
1. Validation logic is separated from JSX, making forms more readable / maintainable
2. We get things out of the box, e.g. `.email()` rather than writing our own bespoke regex
3. Yup can optionally transform as it validates, and this transformed value gets passed to RHF's submit handler. An example of this is trimming or lowercasing strings
If this PR goes in, I'll make another to switch the Create Availability form over to use yup as well.
> APPT-727: Use schema validation with React Hook Form

- infrastructure/resources/high_load_functions.tf
- infrastructure/resources/servicebus_functions.tf
- infrastructure/resources/timer_functions.tf
Timer function app should only have time triggered functions
HTTP function app should have all HTTP functions enabled (apart from highload HTTP functions)
Highload function app should only have HTTP functions that are determined as highload.
Service Bus function app should only have service bus consumers enabled
> APPT-742 - Enable functions in the correct function apps

- src/api/Nhs.Appointments.Api/Functions/ConfirmProvisionalBookingFunction.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/ConfirmBooking.feature
Updated joint bookings error to match single bookings with 410 status code "the requested resource is no longer available and has been removed permanently".
Also added 412 to the swagger document as this was missing
> error code updated to 410 for joint bookings plus 412 to the swagger document

- features/stag.feature.flags.json
We need to performance test Joint Bookings. In order to do this, we need to enable its feature flag in Staging. 
For various reasons, this can currently only be done in Staging and can't be done in Int. I don't like letting Staging deviate from what's in Production, but frankly it already has and until we get a separate perf environment this is the world we're in.
> SRE-402: Enable joint bookings in staging

- azure-pipelines-feature-toggles.yml
We're currently triggering the feature toggles pipeline when a PR is made or when a PR is merged into main. This pipeline should only ever be ran manually through the DevOps UI, so this PR removes the automatic triggers.
> Prevent the feature toggles pipeline from running on PRs

- scripts/pipeline-templates/deploy.yml
`ubuntu-latest` is no longer recognising `terraform` as a valid CLI command. Either because it has been removed or because of some other build agent change. 
This PR adds in a manual step which installs terraform, using one of the terraform install extensions which has been added to our DevOps tenant. 
Ideally, this should be `TerraformInstaller@0`, but using this results in a conflict with the following message:
>The task name TerraformInstaller is ambiguous. Specify one of the following identifiers to resolve the ambiguity: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller, JasonBJohnson.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller
I think this is because someone has added 2 separate installers to our …
> APPT-XXX: Add terraform install step

- src/api/Nhs.Appointments.Core/IUserStore.cs
- src/api/Nhs.Appointments.Core/UserService.cs
- src/api/Nhs.Appointments.Persistance/UserStore.cs
- tests/Nhs.Appointments.Core.UnitTests/UserServiceTests.cs
- tests/Nhs.Appointments.Persistance.UnitTests/UserStoreTests.cs
The notifications are being sent with the wrong information. This is due to Users having the same roles at different sites. This changes makes the store works in a single scope, returning only the original roles that are relevant for change (scope).
> make user role change only return its scope so that notifications dont consider roles that arent relevant as they are not part of the scope

- infrastructure/resources/app_configuration.tf
I was trying to lessen our continual problems with Azure App Configuration by reducing the soft delete retention days to the minimum permitted number, 1. 
This forces terraform to re-create the resource (as seen in screenshot below), which we're not allowed to do because we're not allowed to delete this god-awful thing. 
So hopefully by allowing this value to remain at its default (7), terraform can update rather then re-create what I think might be the worst steaming pile of manure Azure has ever created.
> APPT-290: Stop trying to reduce soft retention days

- azure-pipelines.yml
- src/client/src/app/lib/components/build-number.test.tsx
- src/client/src/app/lib/components/build-number.tsx
- src/client/src/app/lib/components/getBuildNumber.ts
- src/client/src/app/lib/components/nhs-anonymous-page.tsx
- src/client/src/app/lib/components/nhs-footer.tsx
- src/client/src/app/lib/components/nhs-page.tsx
- src/client/src/app/login/page.tsx
- src/client/testing/tests/build-number.spec.ts
I admit this PR is a bit of a hail mary, I only want to see this get as far as the DEV environment. 
We know the `BUILD_NUMBER` is correctly set as an ENV var in the Azure web app resource, yet isn't pulling through like `AUTH_HOST` and `NBS_API_BASE_URL`. Frustratingly, it does when it's set as an ENV var during docker-compose and started locally, so I can't replicate this issue locally. It might be something to do with us running NextJS as a standalone app. 
Screenshots to prove problem:
> APPT-678: Build number investigations

- src/client/src/app/lib/services/appointmentsService.ts
- src/client/src/app/lib/services/availabilityCalculatorService.ts
- src/client/src/app/site/[site]/view-availability/daily-appointments/page.tsx
- src/client/src/app/site/[site]/view-availability/week/view-week-availability-page.tsx
Small missed edge case from me with the previous PR https://github.com/NHSDigital/nbs-appointments-management-service/pull/638 
When running the API in a different timezone also, I wanted to double check that the comprehensive combination of node timezone and the session tests still passed.
I noticed that the DailyAppointments page fails the tests in this case. This is because it passes the datetime info into the booking query to the API in UTC format, when it should be in the datetime timezone unspecified format (secretly UK datetime).
Fundamentally, datetimes passed to the backend and parsed as a C# DateTime should be in the EXACT same format as the database string format: i.e "from": "2025-07-01T09:40:00".
We don't specify in the API that datetime objects are UK or do any conversions, …
> APPT-749 Fix dateTime issue when the API is ran in a different timezone

- docker-compose.yml
- src/client/testing/tests/create-availability/create-availability.spec.ts
- src/client/testing/tests/view-availability/add-session.spec.ts
- src/client/testing/tests/view-availability/view-week-availability.spec.ts
Dates for the Playwright tests are generated dynamically to test timezone functionality. This means we don't know for certain which dates assertions will be written against.
Some assertions are doing pattern matching rather than exact searches, which is causing errors like the following when there are other similar dates on the page:
This PR skips these tests for now to unblock other work
> APPT-867: Skip breaking tests

- src/api/Nhs.Appointments.Api/Functions/QueryAvailabilityFunction.cs
- src/api/Nhs.Appointments.Api/Functions/QueryBookingsFunction.cs
- src/api/Nhs.Appointments.Core/AllocationState.cs
- src/api/Nhs.Appointments.Core/AllocationStateService.cs
- src/api/Nhs.Appointments.Core/AvailabilityCalculator.cs
- src/api/Nhs.Appointments.Core/AvailabilityQueryService.cs
- src/api/Nhs.Appointments.Core/BookingQueryService.cs
- src/api/Nhs.Appointments.Core/BookingWriteService.cs
- src/api/Nhs.Appointments.Core/IAllocationStateService.cs
- src/api/Nhs.Appointments.Core/IAvailabilityQueryService.cs
- src/api/Nhs.Appointments.Core/IAvailabilityStore.cs
- src/api/Nhs.Appointments.Core/IBookingsDocumentStore.cs
- src/api/Nhs.Appointments.Persistance/AvailabilityDocumentStore.cs
- src/api/Nhs.Appointments.Persistance/BookingCosmosDocumentStore.cs
- tests/Nhs.Appointments.Core.UnitTests/AllocationState/AllocationStateServiceTestBase.cs
- tests/Nhs.Appointments.Core.UnitTests/AllocationState/IdempotencyTests.cs
- tests/Nhs.Appointments.Core.UnitTests/AllocationState/MultiServiceTests.cs
- tests/Nhs.Appointments.Core.UnitTests/AllocationState/SingleServiceTests.cs
- tests/Nhs.Appointments.Core.UnitTests/AvailabilityCalculatorTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BookingQueryServiceTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BookingWriteServiceTests.cs
As a rule of thumb we should never be calculating availability without considering the entire state for that slot. This PR removes any filtering on service for the new interfaces
> remove services filter from the availability calculations

- src/api/Nhs.Appointments.Api/Functions/SetUserRolesFunction.cs
- src/client/src/app/site/[site]/users/manage/wizard-steps/email-step.test.tsx
- src/client/src/app/site/[site]/users/manage/wizard-steps/email-step.tsx
- src/client/src/app/site/[site]/users/page.tsx
- src/client/src/app/site/[site]/users/users-page.test.tsx
- src/client/src/app/site/[site]/users/users-page.tsx
- src/client/src/app/testing/data.ts
- tests/Nhs.Appointments.Api.UnitTests/Functions/SetUserRolesFunctionTests.cs
Small changes to match AC on 605/704/706
- Update validation message to match
- Hide Edit / Remove button on Okta users if they've been added and then the feature flag has been disabled again
Edge case but had a discussion with Dave E on point 2 as previously it would show an error on the front end if trying to edit an Okta user when the Okta feature flag has been disabled again.
> APPT-704/706/605 - Minor updates to meet AC

- infrastructure/environments/dev/main.tf
- infrastructure/environments/int/main.tf
- infrastructure/environments/prod/main.tf
- infrastructure/environments/stag-ukw/main.tf
- infrastructure/environments/stag/main.tf
- infrastructure/resources/high_load_functions.tf
- infrastructure/resources/http_functions.tf
- infrastructure/resources/servicebus_functions.tf
- infrastructure/resources/timer_functions.tf
- infrastructure/resources/variables.tf
We hit an issue on int where uploading 244 Okta users caused the BulkImportFunction to hit it's default timeout (5 minutes) so for staging / production we want to enable the high load function for this which has a longer timeout (30 minutes as default).
Once we've figured out a limit on staging for high load, I will work with Anna to workout a plan over a number of weeks to upload all users (both nhs & Okta) so that we don't hit the timeout.
> APPT-880 - Enabling the high load function for Bulk Import

- azure-pipelines-feature-toggles.yml
- features/dev.feature.flags.json
- features/int.feature.flags.json
- features/scripts/import-flags.ps1
- features/stag.feature.flags.json
There is no Jira ticket associated with this. The purpose of this PR is to clean up the feature toggles (disable joint bookings) and to add the --strict param to the import flags script. This new param means that it will override all of the config in the app config. Meaning flags that are not present in the imported json will be removed from app config.
> Add --strict to feature toggles import

- azure-pipelines.yml
- data/CosmosDbSeeder/items/dev/core_data/global_roles.json
- data/CosmosDbSeeder/items/int/core_data/global_roles.json
- data/CosmosDbSeeder/items/local/core_data/global_roles.json
- data/CosmosDbSeeder/items/local/core_data/zzz_test_user_2.json
- data/CosmosDbSeeder/items/prod/core_data/global_roles.json
- data/CosmosDbSeeder/items/stag/core_data/global_roles.json
- nbs-manage-your-appointments.sln
- src/client/testing/tests/manage-user/user-management-permissions.spec.ts
- tests/CosmosDbSeederTests/CosmosDbSeederTests.csproj
- tests/CosmosDbSeederTests/GlobalRolesDocument.cs
- tests/CosmosDbSeederTests/GlobalRolesTests.cs
This PR adds `users:manage` to the list of permissions given to admin users. 
It also clears up some inconsistencies between global roles in each environment and adds tests to assert their equivalence. The list of changes is described [on the ticket](https://nhsd-jira.digital.nhs.uk/browse/APPT-802) and also here:
- The system:auditer role has been deleted entirely
- The system:admin-user has been removed from system:all-permissions
- The system-run-reminders and system:run-provisional-sweep roles have been added to system:all-permissions in all environments
- The system:data-importer has been removed from system:admin-user in all environments
> APPT-802: Synchronise global roles and add user manager to admin permissions

- src/api/Nhs.Appointments.Api/Functions/SetUserRolesFunction.cs
- src/api/Nhs.Appointments.Core/Okta/OktaService.cs
- tests/Nhs.Appointments.Core.UnitTests/OktaServiceTests.cs
Attempting to add or edit an Okta user with 24 hours of first creating them is causing an error. 
This is because of a bug in some OktaService logic which assesses if they're provisioned (i.e. invited to okta but not yet activated), and re-activates that provisioning request if it's expired (i.e. they didn't activate their account within 24 hours). This logic was returning an unsuccessful result if they were provisioned but within that 24 hour period, but it should've been returning a success. 
This PR fixes this bug and also re-writes the service to be a bit clearer/more readable.
> APPT-885: Fix Okta provisioning bug

- src/api/Nhs.Appointments.Core/Okta/IOktaUserDirectory.cs
- src/api/Nhs.Appointments.Core/Okta/OktaLocalUserDirectory.cs
- src/api/Nhs.Appointments.Core/Okta/OktaService.cs
- src/api/Nhs.Appointments.Core/Okta/OktaUnimplementedUserDirectory.cs
- src/api/Nhs.Appointments.Core/Okta/OktaUserDirectory.cs
- src/api/Nhs.Appointments.Core/Okta/OktaUserResponse.cs
- src/api/Nhs.Appointments.Core/Okta/OktaUserStatus.cs
- src/api/Nhs.Appointments.Core/Okta/ServiceProviderExtensions.cs
- tests/Nhs.Appointments.Core.UnitTests/OktaServiceNotImplementedTests.cs
- tests/Nhs.Appointments.Core.UnitTests/OktaServiceProviderExtensionsTests.cs
- tests/Nhs.Appointments.Core.UnitTests/OktaServiceTests.cs
Solves one Okta bug, and temporarily patches over another. 
Bug 1: High load, Service bus and Timer functions were still registering the Okta API through DI but lacked the config for it. This was triggering exceptions when trying to read the PEM token. There is now an unimplemented Okta store which is registered instead if this config is missing. An added benefit of this is failing fast if Okta functions are ever used in those functions. 
Bug 2: Even when I grant our Okta API service account every single permission in the list, we are still receiving an unauthorised response when trying to reactivate users. This is causing the service to fail when it encounters a Provisioned user who was provisioned over 24 hours ago (i.e. the email was sent out but the user never configured their …
> APPT-898: Okta bug fixes

- src/client/testing/tests/view-availability/add-session.spec.ts
Navigate to relevant month for each test rather than hoping daysFromToday(x) is within the current month view.
> APPT-XXX Fix add-session E2E test bug and flakiness. 

- azure-pipelines-bulk-data.yml
This is only a temporary change so we can apply the sites & users to production. APPT-954 has been created to revert this change once the import has been done and signed off.
> APPT-953 - Adding prod as an environment option for the old bulk import

- src/api/Nhs.Appointments.Api/Validators/SetSiteDetailsValidator.cs
- src/client/src/app/lib/components/form-controls/decimal.tsx
- src/client/src/app/lib/components/form-controls/phoneNumber.tsx
- src/client/src/app/lib/types/index.tsx
- src/client/src/app/site/[site]/details/edit-details/edit-details-form.tsx
- src/client/src/app/site/[site]/details/edit-details/edit-site-details-form-schema.test.ts
- src/client/src/app/site/[site]/details/edit-details/edit-site-details-form-schema.ts
- tests/Nhs.Appointments.Api.Integration/Scenarios/SiteManagement/UpdateSiteDetails.feature
We're not currently validating the Lat/Long co-ordinates when they're edited through MYA itself. 
This is part 1 of 2, which just adds our validation to the frontend. Part 2 will be to add the same validation to the backend API.
Also doubles up as a PR for APPT-864, which is to permit the empty string as a valid entry for the Phone Number field
> APPT-863: Validate coordinates in frontend. APPT-864: Allow empty phone number

- data/CosmosDbSeeder/items/dev/core_data/global_roles.json
- data/CosmosDbSeeder/items/int/core_data/global_roles.json
- data/CosmosDbSeeder/items/local/core_data/global_roles.json
- data/CosmosDbSeeder/items/prod/core_data/global_roles.json
- data/CosmosDbSeeder/items/stag/core_data/global_roles.json
Had a discussion with Lauren and Jack and opted to go down the route of giving existing admin users the permission to import data via the bulk upload rather than it being a specific role so this PR also remove the `system:data-importer` role.
Integration tests for the bulk import are currently in a separate PR - hence why they haven't been amended here.
> APPT-970 - Removing the data-importer role and adding it as a permission to the admin role

- src/client/src/app/site/[site]/create-availability/wizard/select-services-step.test.tsx
- src/client/src/app/site/[site]/create-availability/wizard/select-services-step.tsx
- src/client/testing/tests/availability/availability.spec.ts
The Select Services step of the Create Availability wizard isn't written to handle multiple services properly. 
This PR fixes the bug with (un)checking services when there are multiple services to choose from.
It also adds in the "Select all" checkbox, which [APPT-931](https://nhsd-jira.digital.nhs.uk/browse/APPT-931) requests.
> APPT-813: Multi service checkboxes. APPT-931: Select All services checkbox

- data/CosmosDbSeeder/items/dev/core_data/notification_config.json
- data/CosmosDbSeeder/items/int/core_data/notification_config.json
- data/CosmosDbSeeder/items/local/core_data/notification_config.json
- data/CosmosDbSeeder/items/stag/core_data/notification_config.json
- tests/CosmosDbSeederTests/BaseCosmosDbSeederTest.cs
- tests/CosmosDbSeederTests/ClinicalServicesTests.cs
- tests/CosmosDbSeederTests/GlobalRolesTests.cs
- tests/CosmosDbSeederTests/NotificationConfigDocument.cs
- tests/CosmosDbSeederTests/NotificationConfigTests.cs
We recently updated all `clinical_services.json` documents with the confirmed services for the Autumn/Winter campaign. 
What we (I) forgot to do, was update the notification config documents with these new IDs. This means that when the NotifyFoo functions are picking up messages from the bus, they are trying to fetch the templateId for services which don't exist. 
This PR fixes the documents and adds some tests to ensure that all Notification Configurations use service Ids which exist in the clinical services document.
> APPT-986: Fix erroneous notification config

- src/api/Nhs.Appointments.Api/FunctionConfigurationExtensions.cs
- src/api/Nhs.Appointments.Api/Notifications/NotificationsConfig.cs
- src/api/Nhs.Appointments.Api/Notifications/ServiceRegistration.cs
- tests/Nhs.Appointments.Api.UnitTests/NotificationsServiceProviderExtensionsTests.cs
- tests/Nhs.Appointments.Api.UnitTests/NotificationsTestServiceProviderExtensions.cs
We've ran into issues on the PERF environment, both when using the APIM stub and a test profile of Gov.Notify. Because the notification consumers run in a separate process, outside of the main booking/querying journeys, they can be safely ignored without invalidation the performance testing. 
We could therefore just leave them erroring and not care, but the problem then is that the dead-letter queue is growing to a huge size and eventually maxing out. When it maxes out, the main BAU functions which try to add events to that queue start erroring out too. So we need a way to consume items from the queues without throwing any errors. 
We already have a FakeNotificationsClient which isn't currently being used. We also have the concept of a "Notifications Provider" which:
- When "none", will …
> APPT-986: Stub out notifications in Perf

- src/client/src/app/lib/components/nhsuk-frontend/expander.test.tsx
- src/client/src/app/lib/components/nhsuk-frontend/expander.tsx
- src/client/src/app/lib/components/nhsuk-frontend/index.tsx
- src/client/src/app/site/[site]/details/edit-details/edit-details-form.tsx
- src/client/src/app/site/[site]/details/edit-details/edit-site-details-form-schema.test.ts
- src/client/src/app/site/[site]/details/edit-details/edit-site-details-form-schema.ts
I made a very silly error when adding in the Lat/Long validation:
- The backend code is correctly validating that the minimum value for Latitude should be **49.8**
- The frontend code is incorrectly validating it as **-49.8** 🤦 
Also, Product/Design have asked for an expander component to be added (screenshots attached) to explain these ranges.
> APPT-863: Fix lat validation and add Expander component

- src/api/Nhs.Appointments.Core/IUserService.cs
- src/api/Nhs.Appointments.Core/IUserStore.cs
- src/api/Nhs.Appointments.Core/UserDataImportHandler.cs
- src/api/Nhs.Appointments.Core/UserService.cs
- src/api/Nhs.Appointments.Persistance/UserStore.cs
- tests/Nhs.Appointments.Core.UnitTests/UserDataImportHandlerTests.cs
- tests/Nhs.Appointments.Persistance.UnitTests/UserStoreTests.cs
Expected behaviour as discussed with Lauren last week:
- If a user has no existing region permissions and the csv file includes region permissions - add them
- If a user has an existing permission to region "R1" and the csv file includes a row with a region permission to "R1" that is classed as an overwrite and the permission will be removed
- If a user has an existing permission to region "R1" and the csv file includes a row with a region permission to "R2", that is classed as an overwrite where permission to "R1" will be removed and it will be replaced by a region permission to "R2"
> Appt 987 - Adding the ability to update / remove regional user permissions

- azure-pipelines.yml
- scripts/pipeline-templates/deploy.yml
- src/client/testing/tests/manage-user/edit-user.spec.ts
**This change is a 2-birds-1-stone change - adding the RFC check in the deploy step at the top will prevent the cases where we are having a production lock state due to a timed out terraform plan step on deployment to staging.**
Add EnterChangeRequest validation step in before any of the deploy actions when the environment is Production.
This stops the terraform plan step from running (and acquiring a Production state lock) when a release is deployed to Staging (since it won't kick off the plan step without this manual validation passing). Once this validation has timed out, the Production stage can be reran (on the day of LIVE deployment) and if the validation passes with an entered CFG, then it will do the plan and acquire the lock and hopefully be successfully deployed and then release …
> APPT-956 & APPT-682 RFC Approval step for Production

- data/CosmosDbSeeder/items/local/booking_data/seed_booking_35.json
- data/CosmosDbSeeder/items/local/index_data/seed_booking_35_index.json
- src/api/Nhs.Appointments.Core/BookingAvailabilityStateService.cs
- src/client/testing/availability.ts
- src/client/testing/page-objects/view-availability-appointment-pages/week-view-availability-page.ts
- src/client/testing/tests/availability/availability.spec.ts
- tests/Nhs.Appointments.Api.Integration/Scenarios/Availability/WeekSummary_MultipleServices.feature
- tests/Nhs.Appointments.Core.UnitTests/BookingAvailabilityState/GetWeekSummaryTests.cs
In the front end, the booked metric is both the supported bookings and the orphaned. I reflected this in my API metric. But the UI adds these two together, so its easier for me to only count supported bookings in the API for consistency and keep allowing the front end to add the two totals together. 
> APPT-1021 Orphaned total is double counted bug fix

- src/client/src/app/site/[site]/availability/edit-services/confirmed/edit-services-confirmed.test.tsx
- src/client/src/app/site/[site]/availability/edit-services/confirmed/edit-services-confirmed.tsx
- src/client/src/app/site/[site]/availability/edit-services/confirmed/page.tsx
- src/client/src/app/site/[site]/availability/edit-services/edit-services-form.tsx
- src/client/src/app/site/[site]/availability/edit-services/page.tsx
- src/client/src/app/site/[site]/view-availability/week/edit-session/edit-session-decision.test.tsx
- src/client/src/app/site/[site]/view-availability/week/edit-session/edit-session-decision.tsx
- src/client/src/app/site/[site]/view-availability/week/edit-session/page.tsx
- src/client/testing/availability.ts
- src/client/testing/page-objects/view-availability-appointment-pages/change-availability-page.ts
- src/client/testing/page-objects/view-availability-appointment-pages/edit-services-confirmed.ts
- src/client/testing/page-objects/view-availability-appointment-pages/edit-services-page.ts
- src/client/testing/tests/availability/availability.spec.ts
- tests/Nhs.Appointments.Api.Integration/Scenarios/CreateAvailability/SetAvailability_MultipleServices.feature
An MVP journey for reducing services for existing sessions for MultipleServices. The button is only available if MS enabled and the session being edited has more than one service.
> APPT-955 Reduce a sessions services - MVP journey

- features/scripts/deploy-feature-toggles.yml
We've recently introduced Approvals and Checks to the Stag and Prod environment (namely the isMain check and the need for >= 2 approvers). These checks are functioning when deploying the main app, but aren't triggering for the feature toggle pipeline. 
This is because the feature toggle pipeline is not tied to one of our [DevOps environments](https://dev.azure.com/nhsuk/covid19.vaccine-booking/_environments). To link them, we need to use a [deployment job](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops) and set the environment property. 
I've also removed the manual approval check since:
- For stag and prod, this check is now replicated outside of the pipeline
- For dev and int, we've been toggling them manually in the Azure Portal …
> APPT-982: Tie feature toggle pipeline to relevant DevOps environment

- data/CosmosDbSeeder/items/dev/core_data/global_roles.json
- data/CosmosDbSeeder/items/int/core_data/global_roles.json
- data/CosmosDbSeeder/items/local/core_data/global_roles.json
- data/CosmosDbSeeder/items/prod/core_data/global_roles.json
- data/CosmosDbSeeder/items/stag/core_data/global_roles.json
- src/client/src/app/site/[site]/view-availability/daily-appointments/page.tsx
- src/client/src/app/site/[site]/view-availability/week/day-card-list.tsx
- src/client/src/app/site/[site]/view-availability/week/day-summary-card.test.tsx
- src/client/src/app/site/[site]/view-availability/week/day-summary-card.tsx
Added a new permission `booking:view-detail` and applied it to availability manager, appointment manager, site details manager, user manager and admin roles. It **has not** been applied to the regional manager role.
> Appt 923 - Daily appointments page permission

- data/CosmosDbSeeder/items/dev/core_data/clinical_services.json
- data/CosmosDbSeeder/items/dev/core_data/notification_config.json
- data/CosmosDbSeeder/items/int/core_data/clinical_services.json
- data/CosmosDbSeeder/items/local/core_data/clinical_services.json
- data/CosmosDbSeeder/items/local/core_data/notification_config.json
- data/CosmosDbSeeder/items/prod/core_data/clinical_services.json
- data/CosmosDbSeeder/items/stag/core_data/clinical_services.json
- src/api/Nhs.Appointments.Api/FunctionConfigurationExtensions.cs
- src/api/Nhs.Appointments.Api/Functions/GetClinicalServicesFunction.cs
- src/api/Nhs.Appointments.Api/Notifications/BookingNotifier.cs
- src/api/Nhs.Appointments.Api/Notifications/IBookingNotifier.cs
- src/api/Nhs.Appointments.Api/Notifications/ServiceRegistration.cs
- src/api/Nhs.Appointments.Core/ClinicalServiceProvider.cs
- src/api/Nhs.Appointments.Core/ClinicalServiceType.cs
- src/api/Nhs.Appointments.Core/IClinicalServiceProvider.cs
- src/api/Nhs.Appointments.Core/NotificationConfigurationService.cs
- src/api/Nhs.Appointments.Persistance/Models/ClinicalServiceDocument.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/SystemFunctions/RunReminders.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/SystemFunctions/RunRemindersFeatureSteps.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/GetClinicalServicesFunctionTests.cs
- tests/Nhs.Appointments.Api.UnitTests/Notifications/BookingNotifierTests.cs
- tests/Nhs.Appointments.Api.UnitTests/NotificationsServiceProviderExtensionsTests.cs
- tests/Nhs.Appointments.Core.UnitTests/ClinicalServiceProviderTests.cs
- tests/Nhs.Appointments.Core.UnitTests/NotificationConfigurationServiceTests.cs
This PR extends the available template parameters for use in GOV.UK Notify, enabling more dynamic and informative appointment notifications for citizens.
Added "vaccine" and "serviceURL" parameters.
> APPT-845 - New notification parameters for new templates

- scripts/pipeline-templates/deploy.yml
I foolishly left this off the original PR, and it's caused an error when attempting to deploy main to dev. 
> APPT-976: Only run tfstate script for pen environment

- src/client/src/app/lib/components/site-list.test.tsx
- src/client/src/app/lib/components/site-list.tsx
Allowing for partial matching on ODS code when searching for sites.
> APPT-870 - Allowing for partial match on ODS code when searching a site

- data/CosmosDbSeeder/items/prod/core_data/notification_config.json
- data/CosmosDbSeeder/items/stag/core_data/notification_config.json
Updating notification configuration for Staging and Production to benefit from new email and sms templates.
Cherry-picking from main branch as it's needed in R2.3. https://github.com/NHSDigital/nbs-appointments-management-service/pull/811
> APPT-845: staging and prod config for notifications

- src/client/testing/tests/availability/availability.spec.ts
Update all dayIncrement tests so that they target data between 21st August onwards. This will buy us a month or so of no flaky collisions (until they collide with the October hard-coded data)
> APPT-1055 Update all dayIncrement tests to buy us a month of time

- features/int.feature.flags.json
- features/prod.feature.flags.json
- features/stag.feature.flags.json
Disable OKTA on Int, Stag and Prod as its not ready
> APPT-1153 Disable OKTA on Int,Stag and Prod.

- postman-collection/Bulk Import.postman_collection.json
- src/api/Nhs.Appointments.Api/Factories/DataImportHandlerFactory.cs
- src/api/Nhs.Appointments.Api/Factories/IDataImportHandlerFactory.cs
- src/api/Nhs.Appointments.Api/FunctionConfigurationExtensions.cs
- src/api/Nhs.Appointments.Core/ApiUserDataImportHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/AdminUserDataImportHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/AdminUserImportRowMap.cs
- src/api/Nhs.Appointments.Core/BulkImport/IDataImportHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/SiteDataImporterHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/SiteMap.cs
- src/api/Nhs.Appointments.Core/BulkImport/UserDataImportHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/UserImportRowMap.cs
- src/api/Nhs.Appointments.Core/Constants/BulkImportType.cs
- src/api/Nhs.Appointments.Core/IUserService.cs
- src/api/Nhs.Appointments.Core/IUserStore.cs
- src/api/Nhs.Appointments.Core/Nhs.Appointments.Core.csproj
- src/api/Nhs.Appointments.Core/UserService.cs
- src/api/Nhs.Appointments.Persistance/UserStore.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/BulkImportFunctionTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BulkImport/AdminUserDataImportHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BulkImport/ApiUserDataImportHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BulkImport/SiteDataImporterHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BulkImport/UserDataImportHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/SiteDataImporterHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/UserDataImportHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/UserServiceTests.cs
Add the ability to add and remove admin users via the bulk upload. Validation is as follows:
- Email address is mandatory
- Must be a valid email address
- Email address must end in nhs.net
1. If an email in the bulk import already exists in the DB, we will delete that user from the DB
2. If an email in the bulk import does not exist in the DB already, add them with only admin permissions
I have also created a new BulkImport folder in the core project and unit test project to clean up the code base a little.
> Appt 1109 - Bulk upload admin users

- infrastructure/resources/variables.tf
Fixing a broken terraform, this adds the variable definition for reporting
> APPT-1042: missing var definition in terraform

- src/api/Nhs.Appointments.Core/Okta/OktaService.cs
- src/api/Nhs.Appointments.Core/Okta/OktaUserDirectory.cs
- src/api/Nhs.Appointments.Core/Okta/ServiceProviderExtensions.cs
- tests/Nhs.Appointments.Core.UnitTests/Nhs.Appointments.Core.UnitTests.csproj
- tests/Nhs.Appointments.Core.UnitTests/Okta/OktaUserDirectoryTests.cs
- tests/Nhs.Appointments.Core.UnitTests/OktaServiceTests.cs
We are fixing 2 issues. 
First one was to convert status mapping switch statement to use userStatus enum value instead of name because of inconsistency in okta enum naming.  
Second issue was that in case of deactivated account, we were trying to create account instead of reactivate and that was failing.
> APPT-1147: Unable to add okta user

- infrastructure/resources/high_load_functions.tf
The bulk import uses the high load function app on staging and the Okta variables were missing so this PR adds those in
> APPT-1192 - Adding okta config variables into the high load functions

- src/api/Nhs.Appointments.Core/BulkImport/AdminUserImportRowMap.cs
- tests/Nhs.Appointments.Core.UnitTests/BulkImport/AdminUserDataImportHandlerTests.cs
Adding in the missed conversion to lowercase on the email before testing if it ended in nhs.net.
> APPT-1109 - Converting email to lowercase before checking it's domain

- postman-collection/Bulk Import.postman_collection.json
- src/api/Nhs.Appointments.Api/Factories/DataImportHandlerFactory.cs
- src/api/Nhs.Appointments.Api/Factories/IDataImportHandlerFactory.cs
- src/api/Nhs.Appointments.Api/FunctionConfigurationExtensions.cs
- src/api/Nhs.Appointments.Core/ApiUserDataImportHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/AdminUserDataImportHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/AdminUserImportRowMap.cs
- src/api/Nhs.Appointments.Core/BulkImport/IDataImportHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/SiteDataImporterHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/SiteMap.cs
- src/api/Nhs.Appointments.Core/BulkImport/UserDataImportHandler.cs
- src/api/Nhs.Appointments.Core/BulkImport/UserImportRowMap.cs
- src/api/Nhs.Appointments.Core/Constants/BulkImportType.cs
- src/api/Nhs.Appointments.Core/IUserService.cs
- src/api/Nhs.Appointments.Core/IUserStore.cs
- src/api/Nhs.Appointments.Core/Nhs.Appointments.Core.csproj
- src/api/Nhs.Appointments.Core/UserService.cs
- src/api/Nhs.Appointments.Persistance/UserStore.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/BulkImportFunctionTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BulkImport/AdminUserDataImportHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BulkImport/ApiUserDataImportHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BulkImport/SiteDataImporterHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BulkImport/UserDataImportHandlerTests.cs
- tests/Nhs.Appointments.Core.UnitTests/UserServiceTests.cs
(cherry picked from commit 7714ebe8881221ba9fe79cf5653ef728f5ad2093)
(cherry picked from commit e3202daf6a475fff173d07e1bf26eccea56f817a)
Add the ability to add and remove admin users via the bulk upload. Validation is as follows:
- Email address is mandatory
- Must be a valid email address
- Email address must end in nhs.net
1. If an email in the bulk import already exists in the DB, we will delete that user from the DB
2. If an email in the bulk import does not exist in the DB already, add them with only admin permissions
I have also created a new BulkImport folder in the core project and unit test project to clean up the code base a little.
> APPT-1109 - (R2.3) Bulk upload admin users

- data/CosmosDbSeeder/items/local/booking_data/seed_booking_20.json
- postman-collection/Appointment Service.postman_collection.json
- src/api/Nhs.Appointments.Api/Functions/CancelBookingFunction.cs
- src/api/Nhs.Appointments.Api/Functions/CancelSessionFunction.cs
- src/api/Nhs.Appointments.Api/Json/JsonDeserializationContext.cs
- src/api/Nhs.Appointments.Api/Json/JsonRequestReader.cs
- src/api/Nhs.Appointments.Api/Json/NullableStringEnumConverter.cs
- src/api/Nhs.Appointments.Api/Models/CancelBookingRequest.cs
- src/api/Nhs.Appointments.Core/Booking.cs
- src/api/Nhs.Appointments.Core/BookingWriteService.cs
- src/api/Nhs.Appointments.Core/IBookingsDocumentStore.cs
- src/api/Nhs.Appointments.Persistance/BookingCosmosDocumentStore.cs
- src/api/Nhs.Appointments.Persistance/Models/BookingDocument.cs
- src/client/src/app/lib/services/appointmentsService.test.ts
- src/client/src/app/lib/services/appointmentsService.ts
- src/client/src/app/site/[site]/appointment/[reference]/cancel/cancel-appointment-page.test.tsx
- src/client/src/app/site/[site]/appointment/[reference]/cancel/cancel-appointment-page.tsx
- src/client/testing/page-objects/view-availability-appointment-pages/daily-appointment-details-page.ts
- src/client/testing/tests/availability/availability.spec.ts
- tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/BookingBaseFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/Cancel_SingleService.feature
- tests/Nhs.Appointments.Api.UnitTests/Functions/CancelBookingFunctionTests.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/CancelBookingRequestValidatorTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BookingWriteServiceTests.cs
- tests/Nhs.Appointments.Persistance.UnitTests/BookingCosmosDocumentStoreTests.cs
Added mandatory cancellation reason selection to the appointment cancellation flow. Reason is stored only upon confirmed cancellation.
> APPT-873 - Cancellation reason

- src/api/Nhs.Appointments.Core/Reports/SiteSummary/SiteSummaryTrigger.cs
- tests/Nhs.Appointments.Core.UnitTests/Reports/SiteSummary/SiteSummaryTriggerTests.cs
Adding Chunking up of date ranges to publishing from the timer function. On perf it's timing out after 5mins on running the messages. Hopefully chunking into 10 days at a time will help
> APPT-1094: chunk message to the bus to resolve running aggregation taking more than 5mins

- src/api/Nhs.Appointments.Api/Functions/ConfirmProvisionalBookingFunction.cs
- src/api/Nhs.Appointments.Api/Models/ConfirmBookingRequest.cs
- src/api/Nhs.Appointments.Core/Booking.cs
- src/api/Nhs.Appointments.Core/BookingWriteService.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/ConfirmBookingFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/Reschedule.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/RescheduleFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/CreateAvailability/BaseCreateAvailabilityFeatureSteps.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/ConfirmProvisionalBookingFunctionTests.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/ConfirmBookingRequestValidatorTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BookingWriteServiceTests.cs
When rescheduling an appointment, the cancellation reason is not needed in the payload as we should automatically use rescheduled by citizen. This PR adds that into the enum and updates the confirm provisional booking endpoint when rescheduling an appointment
- [x My code generates no new .NET warnings (in the future these will be treated as errors)
> APPT-1229 - Automatically using the rescheduled by citizen cancellation reason when rescheduling an appointment

- src/api/Nhs.Appointments.Api/Functions/ConfirmProvisionalBookingFunction.cs
- src/api/Nhs.Appointments.Api/Models/ConfirmBookingRequest.cs
- src/api/Nhs.Appointments.Core/Booking.cs
- src/api/Nhs.Appointments.Core/BookingWriteService.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/ConfirmBookingFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/Reschedule.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/RescheduleFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/CreateAvailability/BaseCreateAvailabilityFeatureSteps.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/ConfirmProvisionalBookingFunctionTests.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/ConfirmBookingRequestValidatorTests.cs
- tests/Nhs.Appointments.Core.UnitTests/BookingWriteServiceTests.cs
When rescheduling an appointment, the cancellation reason is not needed in the payload as we should automatically use rescheduled by citizen. This PR adds that into the enum and updates the confirm provisional booking endpoint when rescheduling an appointment
src="https://github.com/user-attachments/assets/e14c8b69-17e2-4257-a1d6-5171ede7f17c" />
- [x My code generates no new .NET warnings (in the future these will be treated as errors)
> APPT-1229 - Automatically using the rescheduled by citizen cancellation reason when rescheduling an appointment (#867)

- src/api/Nhs.Appointments.Api/Functions/GetSitesByAreaFunction.cs
- src/api/Nhs.Appointments.Api/Models/GetSitesByAreaRequest.cs
- src/api/Nhs.Appointments.Api/Validators/GetSitesByAreaRequestValidator.cs
- src/api/Nhs.Appointments.Core/IAvailabilityStore.cs
- src/api/Nhs.Appointments.Core/Site.cs
- src/api/Nhs.Appointments.Core/SiteService.cs
- src/api/Nhs.Appointments.Persistance/AvailabilityDocumentStore.cs
- src/api/Nhs.Appointments.Persistance/ITypedDocumentCosmosStore.cs
- src/api/Nhs.Appointments.Persistance/TypedDocumentCosmosStore.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/SiteManagement/SiteSearch.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/SiteManagement/SiteSearchFeatureSteps.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/GetSitesByAreaFunctionTests.cs
- tests/Nhs.Appointments.Api.UnitTests/NotificationsTestServiceProviderExtensions.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/GetSitesByAreaRequestValidatorTests.cs
- tests/Nhs.Appointments.Core.UnitTests/SiteServiceTests.cs
Update to the GetSitesByAreaFunction to allow new optional filtering to be used by NBS to restrict the long/lat area results to only return sites that support the service being queried (this means that a site has posted ANY availability within the daterange, it doesn't mean they have capacity remaining - i.e we aren't doing full allocation and free slot checks at this top level stage)
This is supposed to be 'temporary' in that we are going to attempt to consolidate this API endpoint and the first api/query call into a new single API endpoint in future (APPT-841)
**Having said that, the intention is for this to go out as a hotfix to address A/W needs, so it needs to be performant and behave as expected.**
Have added a LOT of integration tests to prove expected behaviours, as well as old …
> APPT-1203 SitesByArea SitesSupportService filtering

- src/client/src/app/reports/download-report-form-schema.ts
- src/client/src/app/reports/download-report-form.tsx
So I created a form schema and wrote lots of unit tests for a form schema. 
... then I forgot to tell the form to USE the schema 🤦 
Also snuck in a minor improvement to the schema as I've found a way to give an object-level test a property-level error path
> APPT-1235: Fix bug in Download Report form

- src/api/Nhs.Appointments.Persistance/DailySiteSummaryStore.cs
- src/api/Nhs.Appointments.Persistance/Models/DailySiteSummaryDocument.cs
Bug Fix for Cancellations not being persisted in reporting aggregation
> APPT-1236: cancelled not being persisted

- data/CosmosDbSeeder/items/local/core_data/site_ABC02.json
- src/api/Nhs.Appointments.Persistance/SiteStore.cs
- src/client/src/app/lib/components/nhsuk-frontend/card.tsx
- src/client/src/app/lib/components/nhsuk-frontend/summary-list.tsx
- src/client/src/app/lib/services/appointmentsService.ts
- src/client/src/app/lib/services/siteService.ts
- src/client/src/app/lib/types/index.tsx
- src/client/src/app/site/[site]/details/edit-site-status/edit-site-status-form.test.tsx
- src/client/src/app/site/[site]/details/edit-site-status/edit-site-status-form.tsx
- src/client/src/app/site/[site]/details/edit-site-status/edit-site-status-page.test.tsx
- src/client/src/app/site/[site]/details/edit-site-status/edit-site-status-page.tsx
- src/client/src/app/site/[site]/details/edit-site-status/page.tsx
- src/client/src/app/site/[site]/details/site-details-page.test.tsx
- src/client/src/app/site/[site]/details/site-details-page.tsx
- src/client/src/app/site/[site]/page.tsx
- src/client/src/app/site/[site]/site-page.tsx
- src/client/src/app/sites/sites-page.test.tsx
- src/client/src/app/styles/global.css
- src/client/src/app/testing/data.ts
- src/client/testing/fixtures.ts
- src/client/testing/page-objects/change-site-details-pages/edit-site-status.ts
- src/client/testing/page-objects/change-site-details-pages/site-details.ts
- src/client/testing/page-objects/view-availability-appointment-pages/month-view-availability-page.ts
- src/client/testing/page-objects/view-availability-appointment-pages/week-view-availability-page.ts
- src/client/testing/tests/availability/availability.spec.ts
- src/client/testing/tests/change-site-details/edit-site-status.spec.ts
- tests/Nhs.Appointments.Api.Integration/Scenarios/SiteManagement/SiteSearchFeatureSteps.cs
- Displaying the site status on the front end (assuming the feature toggle is enabled)
- New site status page to update the status (also behind feature toggle & site manage permission)
- Raises a notification on success for either update (online -> offline / offline -> online)
- Unit tests
- E2e tests
- Slight re-design of the buttons on the site edit details page
- Re-order of the site edit details page so site details is now at the top
> Appt 1210 - Site Status front end

- data/CapacityDataExtract/CapacityDataExtract.cs
- data/DataExtract/DataExtractWorker.cs
Lowering days from 90 to 60 temporarily to stop time out of capacity report. This will need rolling back once the the extracts are stable again
> Appt 1239/lower days 60

- src/client/src/app/site/[site]/availability/edit-services/confirmed/page.tsx
Updating the date parameter on the edit session back to week view back link to the correct date
> APPT-1240 - Correcting the back to week view link on edit session confirmation page

- src/client/src/app/site/[site]/availability/edit-services/confirmed/page.tsx
(cherry picked from commit e8039bc4c347c1510d7b0ad0284649c490b72553)
(#891)
Updating the date parameter on the edit session back to week view back link to the correct date
> Appt 1240 - Fixing the link on the back to week link on edit session confirmation page

- src/api/Nhs.Appointments.Api/Validators/GetSitesByAreaRequestValidator.cs
- src/api/Nhs.Appointments.Core/SiteService.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/SiteManagement/SiteSearch.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/SiteManagement/SiteSearchFeatureSteps.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/GetSitesByAreaRequestValidatorTests.cs
- tests/Nhs.Appointments.Core.UnitTests/SiteServiceTests.cs
Resolved conflicts against the Online/Offline status work. This needs verifying.
tests/Nhs.Appointments.Api.Integration/Scenarios/SiteManagement/SiteSearchFeatureSteps.cs tests/Nhs.Appointments.Core.UnitTests/SiteServiceTests.cs
(cherry picked from commit 8766f47e999b0682ab9a1711d2578ad099a41f19)
To ensure NBS do not use this potentially non-performant endpoint for busier services, the new optional parameters can only be used when 'RSV:Adult' and 'Flu:2_3' are provided (separately).
Additionally, I have realised a lot of the slowness will have come from the fact that we aren't caching these expensive operations, and this can be acheived by setting a key for the specific site, service and date range (with value of true/false whether the site supports that service). This should improve …
> APPT-1249 RSV/FLU2:3 validation and memory caching (#895)

- data/CapacityDataExtract/CapacityDataConverter.cs
- data/CapacityDataExtract/CapacityDataExtract.cs
- data/CapacityDataExtract/Documents/SiteSessionInstance.cs
- data/DataExtract/DataExtractWorker.cs
- tests/CapacityDataExtracts.UnitTests/CapacityDataConverterTests.cs
Speed improvements for Capacity Extract. From over 1 hour to 1 minute
> Appt 1239: Improve speed capacity report

- src/client/src/app/lib/services/timeService.test.ts
- src/client/src/app/lib/services/timeService.ts
- src/client/src/app/reports/download-report-form-schema.test.ts
- src/client/src/app/reports/download-report-form-schema.ts
Ensuring the string in the date picker can be parsed into a date before parsing it to UK time which was preventing an error from showing on the screen.
> APPT-1235 - Ensuring the date picker contains a valid date before trying to parse to uk time

- src/client/testing/tests/availability/availability.spec.ts
> APPT-XXX Skip the month view tests until we can generate the data more consistently

- src/client/src/app/eula/page.tsx
- src/client/src/app/lib/components/contact-us.tsx
- src/client/src/app/lib/components/nhs-footer.tsx
- src/client/src/app/lib/components/nhsuk-frontend/back-link.tsx
- src/client/src/app/lib/components/nhsuk-frontend/footer.test.tsx
- src/client/src/app/lib/components/nhsuk-frontend/footer.tsx
- src/client/src/app/lib/components/nhsuk-frontend/summary-list.tsx
- src/client/src/app/lib/components/nhsuk-frontend/tabs.tsx
- src/client/src/app/login/log-in-link.tsx
- src/client/src/app/reports/download-report-confirmation.tsx
- src/client/src/app/site/[site]/site-page.test.tsx
When using the NextJS `<Link>` component, routes are prefetched by default to speed up page transitions. This behaviour can be read about here https://nextjs.org/docs/app/guides/prefetching. 
This is undesirable behaviour for external routes, such as the Okta login link, so this PR disables those. 
(it also fixes some tsc errors in some tests)
> APPT-XXXX: Stop prefetching external links

- src/client/src/app/lib/components/nhsuk-frontend/warning-callout.tsx
- src/client/src/app/lib/components/refresh-button.tsx
- src/client/src/app/login/page.tsx
- src/client/src/app/not-found.tsx
- src/client/testing/tests/availability/availability.spec.ts
- tests/Nhs.Appointments.Api.UnitTests/Audit/FunctionMiddlewareTests.cs
Cherry picks the temporary warning banner onto the 2.3 release branch. 
Also cherry picks several required test skips.
Cherry picked commits (from main): 
- 89ed57733731c443c98bfdb9fb605bf85df2b5ad
- 6a09ff52b4f850ba6960b9f565feb1f63e9b4e7c
- 203b69ba8dba29bb64c6106f22d68040d061129d
- 
> APPT-1274: Cherry-pick warning banner

- src/client/src/app/lib/components/nhsuk-frontend/warning-callout.tsx
- src/client/src/app/lib/components/refresh-button.tsx
- src/client/src/app/login/page.tsx
- src/client/src/app/not-found.tsx
- src/client/testing/tests/availability/availability.spec.ts
- tests/Nhs.Appointments.Api.UnitTests/Audit/FunctionMiddlewareTests.cs
Description
Cherry picks the temporary warning banner onto the 2.4 release branch.
Also cherry picks several required test skips.
Cherry picked commits (from main):
https://github.com/NHSDigital/nbs-appointments-management-service/commit/89ed57733731c443c98bfdb9fb605bf85df2b5ad
https://github.com/NHSDigital/nbs-appointments-management-service/commit/6a09ff52b4f850ba6960b9f565feb1f63e9b4e7c
https://github.com/NHSDigital/nbs-appointments-management-service/commit/63a28b5fb07607f1629d41a23cfe5765e1661434
Checklist:
My work is behind a feature toggle (if appropriate)
If my work is behind a feature toggle, I've added a full suite of tests for both the ON and OFF state
The ticket number is in the Pull Request title, with format "APPT-XXX: My Title Here"
I have ran npm tsc / lint …
> APPT-1274: 2.4 Cherry-pick warning banner and flaky tests

- src/api/Nhs.Appointments.Api/Validators/ConfirmBookingRequestValidator.cs
- tests/Nhs.Appointments.Api.UnitTests/Validators/ConfirmBookingRequestValidatorTests.cs
The ConfirmBookingRequest validator is not currently checking that the related (joint) bookings don't include the primary booking reference. This PR adds that check in, but I've also taken the liberty of adding some others: 
- Related bookings is now checked for duplicates
- Related bookings is now checked for null / empty items
- Related bookings is now checked to not include the primary reference (actual goal of ticket)
- Booking to reschedule is now checked to not be the primary reference
- Related bookings is now checked to not include the booking to reschedule
Fixes # (APPT-764)
> APPT-764: Improve ConfirmBookingRequest validator

- src/api/Nhs.Appointments.Core/HasConsecutiveCapacityFilter.cs
- tests/Nhs.Appointments.Api.Integration/JointBookingsSerialToggleCollection.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Availability/AvailabilityBaseFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Availability/JointBookings/JointBookingsAvailabilityFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/Availability/JointBookings/JointBookings_Disabled.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/Availability/JointBookings/JointBookings_Enabled.feature
- tests/Nhs.Appointments.Core.UnitTests/HasConsecutiveCapacityFilterTests.cs
- tests/Nhs.Appointments.Core.UnitTests/Nhs.Appointments.Core.UnitTests.csproj
The Joint Bookings code was not correctly handling the case where two slots occur in parallel, causing the wrong capacity to be reporting and also causing the final slot in the list to incorrectly report capacity where there is in fact none.
Khurram did a fantastic job providing specific test cases for this, so I've reproduced the bug by replicating those in the unit tests.
Fixes # (APPT-767)
> APPT-767: Consecutive count bug

- src/client/src/app/site/[site]/details/edit-site-status/edit-site-status-form.test.tsx
- src/client/src/app/site/[site]/details/edit-site-status/edit-site-status-form.tsx
Adding missing text on change site status screen
> APPT-1293 - Adding missing site status label onto the site status form page

- src/api/Nhs.Appointments.Api/Functions/CancelDayFunction.cs
- src/client/src/app/lib/components/session-summary-table.test.tsx
- src/client/src/app/lib/components/session-summary-table.tsx
- src/client/src/app/lib/services/appointmentsService.ts
- src/client/src/app/lib/types/index.tsx
- src/client/src/app/site/[site]/cancel-day/cancel-day-form.test.tsx
- src/client/src/app/site/[site]/cancel-day/cancel-day-form.tsx
- src/client/src/app/site/[site]/cancel-day/page.tsx
- src/client/src/app/site/[site]/view-availability/week/day-summary-card.test.tsx
- src/client/src/app/site/[site]/view-availability/week/day-summary-card.tsx
This also includes the front end additions for APPT-1176
- Adding content to the cancel a day page
- Hooking it up to the new GetDaySummary and CancelDay endpoints
- Unit tests
- E2e tests will come later as further screens in the cancel day journey are yet to be developed
> Appt 1178 - Cancel day page which is hooked up to the new endpoint

- features/dev.feature.flags.json
- features/int.feature.flags.json
- features/pen.feature.flags.json
- features/perf.feature.flags.json
- features/prod.feature.flags.json
- features/stag.feature.flags.json
Enable Site Status filter on all environments
> APPT-1319: Enable site status feature

- features/dev.feature.flags.json
- features/int.feature.flags.json
- features/pen.feature.flags.json
- features/perf.feature.flags.json
- features/prod.feature.flags.json
- features/stag.feature.flags.json
**(cherry picked from commit a18d47a68818331783c161b3b92adf7169afe18f)**
Enable Site Status filter on all environments
> Appt 1319: cherry pick to release 2.5

- infrastructure/environments/int/main.tf
- infrastructure/environments/int/variables.tf
- infrastructure/resources/locals.tf
This PR disables the query availability on the http function app, as it should always be going to the highload function app via the Frontdoor. It also makes INT use the new Akamai URL.
Before the this can be merged -
Part 1 failed due to naming conflict of the endpoint on the frontdoor, resolved in [Part 1.1](https://github.com/NHSDigital/nbs-appointments-management-service/pull/941)
Frontdoor created and available [here ](https://portal.azure.com/#@nhschoices.net/resource/subscriptions/2cf44e0d-817d-4596-b471-0788f8a14ab2/resourceGroups/nbs-mya-rg-int-uks/providers/Microsoft.Cdn/profiles/nbs-mya-fd-int-uks/overview)@DACA16 to create infra ticket - REQ0274933
New URLs setup - 
[e.nhswebsite-integration.nhs.uk/manage-your-appointments/login](http://e.nhswebsite-integration.nhs.uk/manage-you …
> APPT-1193: Part 2 Use Highload function app for availability and move host to akamai

- src/api/Nhs.Appointments.Api/Functions/GetAuthTokenFunction.cs
- src/client/src/app/auth/set-cookie/route.ts
We've seen some errors thrown from the `GetAuthTokenFunction` when it has been invoked with a correct query string parameter but no request body. 
Rather than mask this error, we should return a `BadRequest` object instead to correctly report that this is an error on the caller's behalf, not an issue in our service.
> APPT-XXX: Improve handling of invalid requests in GetAuthToken

- scripts/pipeline-templates/deploy.yml
We've enabled the high load function app on int, but forgotten to include it in the deploy step of the pipeline.
> APPT-XXX: Include int in the envs we deploy high load functions too

- src/client/src/app/lib/services/timeService.test.ts
- src/client/src/app/lib/services/timeService.ts
- src/client/src/app/site/[site]/availability/edit/edit-session-time-and-capacity-form.test.tsx
- src/client/src/app/site/[site]/availability/edit/edit-session-time-and-capacity-form.tsx
- src/client/src/app/site/[site]/availability/edit/edit-start-time/edit-session-start-time-form.test.tsx
- src/client/src/app/site/[site]/availability/edit/edit-start-time/edit-session-start-time-form.tsx
- src/client/src/app/site/[site]/availability/edit/edit-start-time/page.tsx
- src/client/src/app/testing/data.ts
Adding a new screen to offer 2 alternative session start times, this screen only appears in the following scenarios:
- Bookings in the session and the session length isn't divisible by the slot length using the new requested start time. E.g. session 9:00-10:00 with slot lengths of 10 minutes and the requested start time is 9:05
---------------------------------------------------------------------------------------------
- If there are no bookings or the slot length is divisible by the new session length - continue as we previously did.
- Unit tests for the above
- There are no e2e tests in this yet as there are other change session tickets in progress which would mean re-doing them so those will come after
> Appt 1282 - Change session start time validation

- src/client/src/app/lib/components/nhs-transactional-page.test.tsx
- src/client/src/app/lib/components/nhs-transactional-page.tsx
- src/client/src/app/site/[site]/availability/cancel/page.tsx
As has been raised during testing 1233, the Reports link is still showing on the Cancel Session page because it's not transactional. This was just missed in the original PR: 
Fixes # ([issue](https://nhsd-jira.digital.nhs.uk/browse/APPT-1233))
> APPT-1233: Make the cancel session page transactional

- src/client/src/app/site/[site]/view-availability/week/day-summary-card.test.tsx
- src/client/src/app/site/[site]/view-availability/week/day-summary-card.tsx
Hiding the cancel day link on the day summary card when a user lacks the permission to manage availability
> APPT-1370 - Hiding the cancel day link if the user lacks permission

- src/client/src/app/site/[site]/view-availability/week/day-summary-card.test.tsx
- src/client/src/app/site/[site]/view-availability/week/day-summary-card.tsx
The 'View cancelled appointments' / 'View manual cancellations' links didn't have a permission check around them. This PR adds those in
> APPT-1370 - Adding a permission check around the daily appointment links on the day card

- src/api/Nhs.Appointments.Persistance/BookingCosmosDocumentStore.cs
- src/client/src/app/site/[site]/cancel-day/cancel-day-form.test.tsx
- src/client/src/app/site/[site]/cancel-day/cancel-day-form.tsx
- src/client/src/app/site/[site]/cancel-day/cancelled-appointments/cancelled-appointments.test.tsx
- src/client/src/app/site/[site]/cancel-day/cancelled-appointments/page.tsx
- src/client/src/app/site/[site]/view-availability/daily-appointments/daily-appointments-page.test.tsx
- src/client/src/app/site/[site]/view-availability/daily-appointments/daily-appointments-page.tsx
- tests/Nhs.Appointments.Persistance.UnitTests/BookingCosmosDocumentStoreTests.cs
- Only cancelling bookings on a day which don't have an already 'Cancelled Status'
- This should fix the numbers displayed on the front end as well
- Only returning the newly cancelled bookings with contact details to prevent duplicate cancelled notifications being sent
- Filtering out bookings with contact details on the front end when displaying bookings without them - this list now also includes bookings without contact details that were already cancelled before the cancel a day functionality was ran (assuming the reason was CancelledBySite)
- Including orphaned appointments in the summary booking count when cancelling a day
- Updating the appointments table to state 'Not provided' when no contact details are provided
> APPT-1372/APPT-1376 - A couple of minor fixups for cancel a day

- src/api/Nhs.Appointments.Api/Functions/CancelSessionFunction.cs
- src/api/Nhs.Appointments.Api/local.feature.flags.json
- src/api/Nhs.Appointments.Core/Features/Flags.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/CancelSessionFunctionTests.cs
In this PR, we are adding feature flag that will disable CancelSession endpoint. At the same time, the feature flag will enable new endpoint for session edit, which will replace CancelSession endpoint. The new endpoint is being developed in APPT-1352.
> APPT-1353: Retire CancelSession endpoint with feature flag

- infrastructure/resources/locals.tf
- infrastructure/resources/web_appservice.tf
Update the web app to use the http functions urls directly instead of going via Akamai and the Frontdoor
> APPT-1386: update NBS_API_BASE_URL and AUTH_HOST to be direct to

- infrastructure/resources/locals.tf
- infrastructure/resources/web_appservice.tf
**(cherry picked from commit 7d1716e1fc0709e86a635fca30dbbd4ca0a925fa)**
Update the web app to use the http functions urls directly instead of going via Akamai and the Frontdoor
> APPT 1386: cherry pick 2.6

- infrastructure/environments/pen/main.tf
- infrastructure/environments/perf-ukw/main.tf
- infrastructure/environments/perf/main.tf
- infrastructure/environments/prod-ukw/main.tf
- infrastructure/environments/prod/main.tf
- infrastructure/environments/stag-ukw/main.tf
- infrastructure/environments/stag/main.tf
- infrastructure/resources/variables.tf
- infrastructure/resources/web_appservice.tf
1. Update to the scale out settings for the MYA web app
- This is increasing from 1 running instance (actually 2 in production) to 4 minimum instances in production
- The default is set to 6 and the minimum is set to 4
- So:
- Idle 6 instances will be available
- Low load but above minimum - scales down to 4
- High load it can scale up to 20
2. Scale out and in rules
- Adopting the recommended settings from our performance test findings
This is a temporary increase, so only adjusting for STAG and PROD
- [ N/A ] My work is behind a feature toggle (if appropriate)
- [ N/A ] If my work is behind a feature toggle, I've added a full suite of tests for both the ON and OFF state
- [ Y ] The ticket number is in the Pull Request title, with format "APPT-XXX: My Title Here"
- [ N/A ] I have ran npm …
> APPT-1389 update to terraform scaling out rules for the web application

- tests/Nhs.Appointments.Api.Integration/Scenarios/AvailabilityCalculations/BestFitFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/AvailabilityCalculations/BestFit_ChangeSessionUpliftDisabled.feature
- tests/Nhs.Appointments.Api.Integration/Scenarios/CancelSession/CancelSessionFeatureSteps.cs
- tests/Nhs.Appointments.Api.Integration/Scenarios/CancelSession/CancelSession_Disabled.feature
As we're going to retire the existing cancel session endpoint, we need to update integration tests to use the new endpoint and update them to use the feature toggle pattern. This also includes changes to the best fit tests as some of them use the same cancel session endpoint.
> Appt 1401 - Update cancel session integration tests

- src/api/Nhs.Appointments.Api/Functions/CancelSessionFunction.cs
- tests/Nhs.Appointments.Api.UnitTests/Functions/CancelSessionFunctionTests.cs
This reverts commit a6474e901afca3987ffec54d00e1dc7d51fb59db.
Reverting the change for retiring the cancel session endpoint as integration tests have now been updated to use the new edit session endpoint.
> Revert "APPT-1252 - Removing the feature flag check on the cancel session endpoint

- data/BookingsDataExtracts/BookingDataConverter.cs
- data/BookingsDataExtracts/BookingDataExtractFields.cs
- data/BookingsDataExtracts/BookingsDataExtract.cs
- tests/BookingDataExtracts.UnitTests/BookingDataConverterTests.cs
Adding booking batch size (when present) to reports
> APPT-1299 - Adding booking batch size (when present) to reports

- src/api/Nhs.Appointments.Api/Functions/GetReportSiteSummaryFunction.cs
Surround string values with quotes when exporting to CSV. Currently commas and other special characters are breaking reports
> Appt 1354: Comma separated strings
