.github/dependabot.yml

- Added dependabot config for npm
- Set to ignore major version updates for now 
- All updates grouped into single PR

APPT-20 Dependabot for npm

---

src/client/src/App.css
src/client/src/Components/SiteIndicator.test.tsx
src/client/src/Components/SiteSetup.tsx
src/client/src/Components/TimeBlocks.test.tsx
src/client/src/Views/DailyBookings.test.tsx
src/client/src/Views/DailyBookings.tsx
src/client/src/Views/EditSiteServices.tsx
src/client/src/Views/ScheduleEditor.tsx
src/client/src/Views/TemplateListView.tsx
src/client/src/Views/WeekTemplateEditor.tsx
src/client/src/index.css

Fixes the alignment of the daily bookings checkboxes and also tidies styling code 
https://nhsd-jira.digital.nhs.uk/browse/STF-471

STF-471 checkbox alignment

---

tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/SiteConfiguration/SiteConfiguration.feature
tests/Nhs.Appointments.Api.Integration/Scenarios/SiteConfiguration/SiteConfigurationFeatureSteps.cs

- Site configuration test feature file and steps added back to integration test project

Reinstate site configuration integration test

---

src/client/src/App.tsx
src/client/src/Components/AppPage.tsx

Having discovered the permission being tested renders the app unusable if the user doesn't have it, we are going to keep the ticket the same and test against a different permission and rectify the app's dependency on the site:get-config permission in other tickets
https://nhsd-jira.digital.nhs.uk/browse/APPT-64

APPT-64 Permission changeover

---

src/api/Nhs.Appointments.Api/Functions/GetRolesFunction.cs
src/api/Nhs.Appointments.Api/Models/GetRolesResponse.cs
src/api/Nhs.Appointments.Core/Role.cs
src/api/Nhs.Appointments.Persistance/Models/RolesDocument.cs
src/client/src/Types/Role.tsx
src/client/src/Views/EditUser.test.tsx
src/client/src/Views/EditUser.tsx
tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/RoleManagement/RoleManagement.feature
tests/Nhs.Appointments.Api.Integration/Scenarios/RoleManagement/RoleManagementFeatureSteps.cs

- Role descriptions added to roles cosmos document
- Frontend displays the description for each role
- Grouped checkboxes together in a fieldset as recommended by NHS style guide
- Updated tests

APPT-127 View role descriptions on assign role page

---

src/api/Nhs.Appointments.Api/Functions/CancelBookingFunction.cs
src/api/Nhs.Appointments.Api/Functions/SetBookingStatusFunction.cs

https://nhsd-jira.digital.nhs.uk/browse/APPT-129

Fixes SetBookingStatus siteId for permission checks

---

docker-compose.yml
mock-data/CosmosDbSeeder/items/index_data/cc2_user.json
mock-data/CosmosDbSeeder/items/index_data/cc_user.json
mock-data/CosmosDbSeeder/items/index_data/global_roles.json
src/new-client/package-lock.json
src/new-client/package.json
src/new-client/src/app/components/table.tsx
src/new-client/src/app/lib/users.ts
src/new-client/src/app/site/[site]/users/manage/assign-roles-form.test.tsx
src/new-client/src/app/site/[site]/users/manage/assign-roles-form.tsx
src/new-client/src/app/site/[site]/users/manage/assign-roles.test.tsx
src/new-client/src/app/site/[site]/users/manage/assign-roles.tsx
src/new-client/src/app/site/[site]/users/manage/find-user-form.test.tsx
src/new-client/src/app/site/[site]/users/manage/find-user-form.tsx
src/new-client/src/app/site/[site]/users/manage/page.test.tsx
src/new-client/src/app/site/[site]/users/manage/page.tsx
src/new-client/src/app/site/[site]/users/page.test.tsx
src/new-client/src/app/site/[site]/users/page.tsx
src/new-client/src/app/testing/data.ts
src/new-client/src/constants.tsx

Basic tasks for managing user role assignments

Appt 145/manage user roles

---

README.md
infrastructure/resources/web.tf

Updates the readme to reflect recent changes to the app, namely:
* How to run the Cosmos DB Seeder
* Expand the document tech stack to include NextJS/React versions

APPT-XXX - Update readme with recent changes

---

src/new-client/testing/log-in.spec.ts
src/new-client/testing/page-objects/oauth.ts
src/new-client/testing/page-objects/root.ts
src/new-client/testing/page-objects/site-selection.ts
src/new-client/testing/testEnvironment.ts

Just a quick mini spike PR to see how using the Page Object Model might look in Playwright - there are myriad ways to achieve this, but this is a starter for ten

Introduce Page Object Model in Playwright tests

---

azure-pipelines.yml
infrastructure/environments/dev/main.tf
infrastructure/resources/api.tf
infrastructure/resources/variables.tf
infrastructure/resources/web.tf

- Updated variables for auth in infrastructure

Fix auth variables for dev

---

azure-pipelines.yml

- Fix to remove unused variable mapping from terraform steps in deploy stage

Appt xxxx/fix pipeline notification var

---

azure-pipelines.yml
docker-compose.yml
infrastructure/environments/dev/main.tf
infrastructure/resources/api.tf
infrastructure/resources/variables.tf
src/api/Nhs.Appointments.Api/Bookings/MakeBookingOptions.cs
src/api/Nhs.Appointments.Api/FunctionConfigurationExtensions.cs
src/api/Nhs.Appointments.Api/Functions/MakeBookingFunction.cs
src/api/Nhs.Appointments.Api/local.settings.json
tests/Nhs.Appointments.Api.UnitTests/Functions/MakeBookingFunctionTests.cs

needed for test - to be upgraded to a feature flag in azure

temporarily disable availability checking

---

src/new-client/src/app/site/[site]/users/page.tsx
src/new-client/src/app/site/[site]/users/remove/page.tsx
src/new-client/src/app/site/[site]/users/users-page.test.tsx
src/new-client/src/app/site/[site]/users/users-page.tsx
src/new-client/src/app/testing/data.ts
src/new-client/testing/create-and-remove-user.spec.ts

Prevent the user from removing their own user permissions at a site

APPT-224: Remove the remove this user button for the currently logged in user

---

src/new-client/src/app/site/[site]/site-page.test.tsx
src/new-client/src/app/site/[site]/site-page.tsx
src/new-client/testing/page-objects/site.ts

Minor changes to copy requested by Khurram / Thomas

APPT-231: Minor copy changes

---

azure-pipelines.yml
docker-compose.yml
infrastructure/environments/dev/main.tf
infrastructure/resources/api.tf
infrastructure/resources/variables.tf
src/api/Nhs.Appointments.Api/Bookings/MakeBookingOptions.cs
src/api/Nhs.Appointments.Api/FunctionConfigurationExtensions.cs
src/api/Nhs.Appointments.Api/Functions/MakeBookingFunction.cs
src/api/Nhs.Appointments.Api/local.settings.json
tests/Nhs.Appointments.Api.UnitTests/Functions/MakeBookingFunctionTests.cs

back out of the changes previously made for this ticket.

remove availability check feature flag

---

azure-pipelines.yml

- Creates folder for https certificate before running dev-certs

Fix dev certs issue

---

src/api/Nhs.Appointments.Api/Functions/TriggerBookingRemindersFunction.cs
src/api/Nhs.Appointments.Persistance/Models/BookingDocument.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/MakeBooking.feature
tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/MakeBookingFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/QueryBookingByNhsNumber.cs

- Add contact details to booking_document model
- Update booking integration tests to include contact details
- Update trigger function to return success result

APPT-344 - contact details to booking document

---

azure-pipelines.yml
infrastructure/environments/int/main.tf
infrastructure/environments/int/variables.tf
scripts/pipeline-templates/deploy.yml

- Add terraform module for int
- Update variable name for service connection and fix parameter usage

APPT-284 - deploy app to integration subscription

---

src/new-client/src/app/site/[site]/create-availability/wizard/capacity-calculation.test.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/capacity-calculation.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/summary-step.test.tsx

Fixes a few bugs in the capacity calculation, and adds in some missing tests

APPT-239: Add tests for capacity calculation and summary step

---

src/new-client/src/app/lib/components/nhs-heading.tsx
src/new-client/src/app/lib/components/nhs-transactional-page.tsx
src/new-client/src/app/lib/components/nhsuk-frontend/date-input.test.tsx
src/new-client/src/app/lib/components/nhsuk-frontend/footer.tsx
src/new-client/src/app/site/[site]/create-availability/page.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/capacity-calculation.test.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/capacity-calculation.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/select-services-step.test.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/select-services-step.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/single-or-repeating-session-step.test.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/single-or-repeating-session-step.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/start-and-end-date-step.test.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/start-and-end-date-step.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/summary-step.test.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/summary-step.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.test.tsx
src/new-client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.tsx
src/new-client/testing/page-objects/create-availability.ts

Updates the content and design of the Create Availability to match V3 of [the prototype](https://manage-appointments-prototype-df29cf21568e.herokuapp.com/v3/session-type)

APPT-399: Update Content and cosmetics in CA wizard

---

src/api/Nhs.Appointments.Api/Consumers/BookingCancelledConsumer.cs
src/api/Nhs.Appointments.Api/Consumers/BookingMadeConsumer.cs
src/api/Nhs.Appointments.Api/Consumers/BookingReminderConsumer.cs
src/api/Nhs.Appointments.Api/Consumers/BookingRescheduledConsumer.cs
src/api/Nhs.Appointments.Api/Functions/ConfirmProvisionalBookingFunction.cs
src/api/Nhs.Appointments.Api/Functions/MakeBookingFunction.cs
src/api/Nhs.Appointments.Api/Json/JsonToObjectSchemaValidation.cs
src/api/Nhs.Appointments.Api/Models/ConfirmBookingRequest.cs
src/api/Nhs.Appointments.Api/Models/MakeBookingRequest.cs
src/api/Nhs.Appointments.Api/Validators/AttendeeDetailsValidator.cs
src/api/Nhs.Appointments.Api/Validators/ConfirmBookingRequestValidator.cs
src/api/Nhs.Appointments.Core/Booking.cs
src/api/Nhs.Appointments.Core/Messaging/EventFactory.cs
src/api/Nhs.Appointments.Core/Messaging/Events/BookingMade.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/ConfirmBookingFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/MakeBookingFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/QueryBookingByNhsNumber.cs
tests/Nhs.Appointments.Api.UnitTests/Consumers/BookingCancelledConsumerTests.cs
tests/Nhs.Appointments.Api.UnitTests/Consumers/BookingMadeConsumerTests.cs
tests/Nhs.Appointments.Api.UnitTests/Consumers/BookingReminderConsumerTests.cs
tests/Nhs.Appointments.Api.UnitTests/Consumers/BookingRescheduledConsumerTests.cs
tests/Nhs.Appointments.Api.UnitTests/Functions/MakeBookingFunctionTests.cs
tests/Nhs.Appointments.Api.UnitTests/Validators/AttendeeDetailsValidatorTests.cs
tests/Nhs.Appointments.Api.UnitTests/Validators/ConfirmBookingRequestValidatorTests.cs
tests/Nhs.Appointments.Api.UnitTests/Validators/MakeBookingRequestValidatorTests.cs
tests/Nhs.Appointments.Core.UnitTests/BookingServiceTests.cs
tests/Nhs.Appointments.Core.UnitTests/EventFactoryTests.cs

Changed contact item to an enum to enforce correct values in requests
Added additional logic to check for empty object

additional fixes to validation for the confirm endpoint

---

src/api/Nhs.Appointments.Api/Notifications/BookingNotifier.cs
src/api/Nhs.Appointments.Api/Notifications/GovNotifyClient.cs
src/api/Nhs.Appointments.Api/Notifications/IPrivacyUtil.cs
src/api/Nhs.Appointments.Api/Notifications/NotificationException.cs
src/api/Nhs.Appointments.Api/Notifications/PrivacyUtil.cs
src/api/Nhs.Appointments.Api/Notifications/ServiceRegistration.cs
tests/Nhs.Appointments.Api.UnitTests/Functions/CancelBookingFunctionTests.cs
tests/Nhs.Appointments.Api.UnitTests/Notifications/BookingMadeNotifierTests.cs
tests/Nhs.Appointments.Api.UnitTests/Notifications/BookingRescheduledNotifierTests.cs
tests/Nhs.Appointments.Api.UnitTests/Notifications/PrivacyUtilTests.cs
tests/Nhs.Appointments.Core.UnitTests/BookingServiceTests.cs

for easier troubleshooting of gov notify issues

additional notification logging and tests

---

src/new-client/src/app/lib/components/nhsuk-frontend/index.tsx
src/new-client/src/app/lib/components/nhsuk-frontend/pagination.tsx
src/new-client/src/app/lib/services/viewAvailabilityService.test.ts
src/new-client/src/app/lib/services/viewAvailabilityService.ts
src/new-client/src/app/lib/types/index.tsx
src/new-client/src/app/site/[site]/view-availability/page.tsx
src/new-client/src/app/site/[site]/view-availability/view-availability-page.test.tsx
src/new-client/src/app/site/[site]/view-availability/view-availability-page.tsx
src/new-client/src/app/site/[site]/view-availability/week/page.tsx
src/new-client/src/app/testing/data.ts

Part 2 includes:
- Pagination
- Logic fixups as the first day of each week was missing from booking count
- Updated tests
- Little bit of code clean up

Appt 337/view availability pagination - PART 2

---

tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/Eula/ConsentToEula.feature
tests/Nhs.Appointments.Api.Integration/Scenarios/Eula/ConsentToEulaFeatureSteps.cs

- Created eula test user to isolate changes to user document for test purposes from main integration test user used to run the tests

Fix EULA integration test

---

src/api/Nhs.Appointments.Core/Booking.cs
src/api/Nhs.Appointments.Core/BookingsService.cs
src/api/Nhs.Appointments.Persistance/BookingCosmosDocumentStore.cs
src/api/Nhs.Appointments.Persistance/Models/BookingDocument.cs
src/api/Nhs.Appointments.Persistance/Models/BookingIndexDocument.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/Booking/BookingBaseFeatureSteps.cs

Date and time of last status update will be tracked in the booking document. This can be exported for downstream data analysis

Record date and time of status updates

---

azure-pipelines-bulk-data.yml
data/CsvDataTool/ApiUserDataImportHandler.cs
data/CsvDataTool/DataImportHandlerFactory.cs
tests/CsvDataTool.UnitTests/CsvProcessorTests.cs

- Updated csv conversion tool to convert api user users

APPT-441 - Add ability to import api user to cosmos

---

data/CosmosDbSeeder/items/local/booking_data/20250701.json
src/client/src/app/lib/components/nhsuk-frontend/tabs.tsx
src/client/src/app/site/[site]/view-availability/daily-appointments/daily-appointments-page.tsx
src/client/src/app/site/[site]/view-availability/daily-appointments/page.tsx

Passing a callback which alters search params from a server to a client component was causing errors, so for now I've abstracted it out to something more generic to fix this error for now.
I also noticed a mismatched ID in the booking data and have hidden the previous page button if page is less than 1.

Change event handler for a different interface

---

infrastructure/resources/database.tf
scripts/pipeline-templates/deploy.yml

Add spacial index to core_data container

Add spacial index to core_data container

---

data/CosmosDbSeeder/items/local/booking_data/seed_booking_01.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_02.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_03.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_04.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_05.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_06.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_07.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_08.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_09.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_10.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_11.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_01_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_02_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_03_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_04_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_05_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_06_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_07_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_08_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_09_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_10_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_11_index.json

APPT-XXX: Create seed scheduled and cancelled bookings for the 1st July 2025

---

src/client/src/app/lib/services/viewAvailabilityService.test.ts
src/client/src/app/lib/services/viewAvailabilityService.ts
src/client/src/app/testing/data.ts

Fixed mismatched booked appointments on monthly vs weekly view

Month and week booking count mismatch

---

docker-compose.yml
infrastructure/resources/api.tf
infrastructure/resources/variables.tf
src/api/Nhs.Appointments.Api/Notifications/ConsoleLogNotifications.cs
src/api/Nhs.Appointments.Api/Notifications/ServiceRegistration.cs

- Add new notification provider setting for preview
- Disable all notification and timed functions for preview

Disable notification and timed functions in preview slot

---

azure-pipelines.yml
scripts/cosmos-build/create_cosmos_db.ps1
scripts/cosmos-build/delete_cosmos_db.ps1

- Add new resource group in integration sub for hosting PR build cosmos accounts

APPT-XXXX - Update resource group for cosmos PR build accounts

---

infrastructure/environments/stag/main.tf
infrastructure/environments/stag/variables.tf
infrastructure/resources/variables.tf
infrastructure/resources/web.tf
src/client/next.config.mjs

This is requires to allow server actions to be invoked when there is a proxy in the way. Azure front door is acting as a proxy so the forwarded header does not match the origin header

adding option to allow proxying of requests in next server actions

---

data/CosmosDbSeeder/items/prod/core_data/attribute_definitions.json
data/CosmosDbSeeder/items/prod/core_data/eula.json
data/CosmosDbSeeder/items/prod/core_data/global_roles.json
data/CosmosDbSeeder/items/prod/core_data/notification_config.json
data/CosmosDbSeeder/items/prod/core_data/well_known_ods_codes.json
data/CosmosDbSeeder/items/stag/core_data/notification_config.json

- Update existing staging config to match the template ids as in gov.notfy portal for staging
- Add prod cosmos config including notification config with template ids for RSV only

APPT-512 - Add notification configuration to staging and prod cosmos documents

---

src/client/src/app/lib/components/nhsuk-frontend/summary-list.tsx
src/client/src/app/site/[site]/site-page.test.tsx
src/client/src/app/site/[site]/site-page.tsx
src/client/testing/create-availability.spec.ts
src/client/testing/page-objects/create-availability.ts
src/client/testing/page-objects/create-availability/summary-page.ts
src/client/testing/utils/date-utility.ts

Fixed all PR Comments for APPT-239 old PR

Fixed all PR Comments

---

src/client/src/app/site/[site]/view-availability/daily-appointments/daily-appointments-page.test.tsx
src/client/src/app/site/[site]/view-availability/daily-appointments/page.tsx

Adding the cancel action to the 'Manual Cancellations' tab in the Daily Appointments view

Appt 578/add action column to manual cancellations tab

---

src/client/src/app/eula/eula-page.test.tsx
src/client/src/app/eula/page.tsx
src/client/testing/page-objects/eula-consent.ts

Wording changes and URL change for the Eula page

Appt 542/eula content update

---

data/CosmosDbSeeder/items/stag/core_data/notification_config.json

Updating email / SMS (where applicable) templateId's in staging for:
- Cancelling an RSV booking
- Updating user roles

APPT-612&613 - Updating staging templateId's

---

src/client/src/app/login/log-in-button.tsx
src/client/src/app/login/page.tsx
src/client/src/middleware.ts
src/client/testing/tests/create-availability/create-availability.spec.ts

Revert https://github.com/NHSDigital/nbs-appointments-management-service/pull/531 
Output missing vars hidden

Appt xxx outputvars

---

src/client/next.config.mjs

Adding redirect config to fix issue with reverse proxy

APPT-596: Redirect Fix

---

src/client/src/app/login/page.tsx

Ideally would toggle this on/off using feature toggle management, but due to time constraints simpler to just hide it for now.

APPT-640 Comment out OKTA login button

---

src/client/next.config.mjs
src/client/src/app/auth/set-cookie/route.ts
src/client/src/app/auth/signOut.ts
src/client/src/app/cookies-policy/cookie-consent-form.test.tsx
src/client/src/app/cookies-policy/cookie-consent-form.tsx
src/client/src/app/error.test.tsx
src/client/src/app/eula/accept-eula-form.tsx
src/client/src/app/lib/components/nhs-anonymous-page.tsx
src/client/src/app/lib/components/nhs-page.test.tsx
src/client/src/app/lib/components/nhsuk-frontend/breadcrumbs.test.tsx
src/client/src/app/lib/components/nhsuk-frontend/header.tsx
src/client/src/app/login/page.tsx
src/client/src/app/not-found.tsx
src/client/src/app/page.tsx
src/client/src/app/site/[site]/create-availability/wizard/days-of-week-step.tsx
src/client/src/app/site/[site]/create-availability/wizard/select-services-step.tsx
src/client/src/app/site/[site]/create-availability/wizard/single-or-repeating-session-step.tsx
src/client/src/app/site/[site]/create-availability/wizard/start-and-end-date-step.tsx
src/client/src/app/site/[site]/create-availability/wizard/summary-step.tsx
src/client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.tsx
src/client/src/app/site/[site]/users/manage/page.tsx
src/client/src/app/sites/page.tsx
src/client/src/app/sites/sites-page.test.tsx
src/client/src/app/sites/sites-page.tsx
src/client/testing/eula.spec.ts
src/client/testing/log-in.spec.ts
src/client/testing/page-objects/oauth.ts
src/client/testing/tests/cookie-acceptance/cookie-management.spec.ts
src/client/testing/tests/manage-user/user-management-permissions.spec.ts

Draft to see how the pipeline fares....

DRAFT: APPT-649: Add sites route

---

data/CosmosDbSeeder/items/int/core_data/notification_config.json
src/api/Nhs.Appointments.Api/Notifications/BookingNotifier.cs
tests/Nhs.Appointments.Api.UnitTests/Notifications/BookingNotifierTests.cs

Added new property called siteLocation to BookingNotifier
Updated rsv email templateIDs for booking made and booking reminder

APPT-212 - Adding siteLocation to booking notifier

---

azure-pipelines.yml
scripts/pipeline-templates/deploy.yml

Reverts NHSDigital/nbs-appointments-management-service#553

Revert "Hotfix/appt 623 support hotfix branches"

---

src/api/Nhs.Appointments.Core/CsvProcessor.cs
src/api/Nhs.Appointments.Core/SiteMap.cs
tests/Nhs.Appointments.Core.UnitTests/SiteDataImporterHandlerTests.cs
tests/Nhs.Appointments.Core.UnitTests/UserDataImportHandlerTests.cs

3/3 - Targeting the 643 branch for now so I avoid merge conflicts when that one goes in 
Also includes an update to the exception message to not show the stack trace.

APPT-687 - Checking the longitude & latitude values are within the range for the UK

---

azure-pipelines.yml
docker-compose.yml
infrastructure/environments/dev/main.tf
infrastructure/environments/dev/variables.tf
infrastructure/environments/int/main.tf
infrastructure/environments/int/variables.tf
infrastructure/environments/prod/main.tf
infrastructure/environments/prod/variables.tf
infrastructure/environments/stag/main.tf
infrastructure/environments/stag/variables.tf
infrastructure/resources/web_appservice.tf
scripts/pipeline-templates/deploy.yml
src/client/.env
src/client/next.config.mjs
src/client/src/app/lib/components/nhs-footer.tsx
src/client/src/app/lib/components/nhsuk-frontend/footer.test.tsx
src/client/src/app/lib/components/nhsuk-frontend/footer.tsx
src/client/testing/page-objects/root.ts
src/client/testing/playwright.env
src/client/testing/testEnvironment.ts
src/client/testing/tests/build-number.spec.ts

Surfaces a Build Number in the footer, hidden both visually and from the accessibility tree. 
This build number is currently just the pipeline ID - we can come up with another scheme if we want

APPT-678: Surface Build Number in frontend

---

src/client/src/app/lib/components/site-list.test.tsx
src/client/src/app/site/[site]/create-availability/wizard/single-or-repeating-session-step.test.tsx
src/client/src/app/site/[site]/create-availability/wizard/time-and-capacity-step.test.tsx

We have several Jest tests which pass but spit out console errors. This PR resolves the following errors:

APPT-XXX: Fix errors in jest tests

---

src/api/Nhs.Appointments.Core/UserDataImportHandler.cs
src/api/Nhs.Appointments.Core/UserImportRowMap.cs
tests/Nhs.Appointments.Core.UnitTests/UserDataImportHandlerTests.cs

Added validation for bulk uploaded okta users. FirstName and LastName is required.

APPT-705 okta bulk upload

---

src/client/src/app/lib/components/nhs-footer.tsx
src/client/testing/page-objects/root.ts

This reverts commit ca4a9c3f4bcb1b56f4c8ed550fdd2a3b37d1e444.

Revert "APPT-689 - Adding accessibility statement to the footer"

---

src/api/Nhs.Appointments.Core/UserService.cs
src/client/src/app/site/[site]/users/manage/assign-roles.test.tsx
src/client/src/app/site/[site]/users/manage/assign-roles.tsx
src/client/src/app/site/[site]/users/manage/find-user-form.test.tsx
src/client/src/app/site/[site]/users/manage/find-user-form.tsx
src/client/src/app/site/[site]/users/remove/page.tsx
tests/Nhs.Appointments.Core.UnitTests/UserServiceTests.cs

Bugs resolved include - APPT-719, APPT-720, APPT-691

resolve case sensitive checks around user email

---

src/api/Nhs.Appointments.Api/Functions/BulkImportFunction.cs
src/api/Nhs.Appointments.Core/UserDataImportHandler.cs
src/api/Nhs.Appointments.Core/UserImportRowMap.cs
tests/Nhs.Appointments.Core.UnitTests/UserDataImportHandlerTests.cs

Also removing the commented out permission check on the bulk import

APPT-615 - Adding OKTA users to OKTA as well via the bulk import

---

scripts/pipeline-templates/deploy.yml

refer to https://github.com/NHSDigital/nbs-appointments-management-service/pull/634/files

missed change for apply terraform

---

src/api/Nhs.Appointments.Api/Functions/GetUserRoleAssignmentsFunction.cs
src/api/Nhs.Appointments.Core/User.cs
src/api/Nhs.Appointments.Persistance/Models/UserDocument.cs
src/client/src/app/lib/types/index.tsx
tests/Nhs.Appointments.Api.UnitTests/Functions/GetUserRoleAssignmentsFunctionTests.cs

FYI - Correct ticket ref is 825, I was in a conversation around 605 when I created the branch name and have only just realised since creating the PR.

APPT-825 - Removing first and last name from the cosmos document

---

data/CosmosDbSeeder/items/prod/core_data/notification_config.json

Email template id updated to support Site Location information in RSV reschedule.
This is to update the prod configuration

APPT-729 - email template id updated for reschedule

---

src/api/Nhs.Appointments.Api/Functions/QueryAvailabilityFunction.cs
src/api/Nhs.Appointments.Core/AllocationState.cs
src/api/Nhs.Appointments.Core/AllocationStateService.cs
src/api/Nhs.Appointments.Core/BookingWriteService.cs
src/api/Nhs.Appointments.Core/IAllocationStateService.cs
tests/Nhs.Appointments.Core.UnitTests/AllocationState/IdempotencyTests.cs
tests/Nhs.Appointments.Core.UnitTests/AllocationState/MultiServiceTests.cs
tests/Nhs.Appointments.Core.UnitTests/AllocationState/SingleServiceTests.cs

Refactor allocation state service

Appt 839/refactor calculation

---

src/client/src/app/site/[site]/users/manage/page.tsx
src/client/src/app/site/[site]/users/manage/set-user-roles-wizard.tsx
src/client/src/app/site/[site]/users/manage/wizard-steps/email-step.test.tsx
src/client/src/app/site/[site]/users/manage/wizard-steps/email-step.tsx
src/client/testing/page-objects/manage-users/email-step.ts
src/client/testing/tests/okta-toggle.spec.ts

This hint text is also behind the Okta feature toggle and will only be displayed if it is enabled.
**Disabled:**
**Enabled:**

APPT-892 - Adding email hint text to new user screen

---

scripts/pipeline-templates/deploy.yml

Allows us to retain releases that go past staging for a Year. Making it easier to rollback to a previous build

APPT-855 - build retention added when staging

---

src/client/src/app/lib/types/index.tsx
src/client/src/app/site/[site]/create-availability/availabilityCreatedEventsTable.test.tsx
src/client/src/app/site/[site]/create-availability/availabilityCreatedEventsTable.tsx
src/client/src/app/testing/data.ts

APPT 896 is a minor UI bug where comma separation was missed for sessions. Templates display correctly

BUG - APPT 896 - Comma seperated list for clinical services in create availability screen

---

src/client/src/app/site/[site]/create-availability/wizard/select-services-step.test.tsx
src/client/src/app/site/[site]/create-availability/wizard/select-services-step.tsx

Product/Test want the `Select all` checkbox to be renamed `Select all services`.

APPT-931: Update select all text

---

tests/Nhs.Appointments.Api.Integration/OktaEnabledSerialToggleCollection.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/BaseFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/UserManagement/AssignRolesToAUserFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/UserManagement/GetUserRoleAssignmentsSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/UserManagement/ProposeCreation/ProposeCreationBaseFeatureSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/UserManagement/ProposeCreation/ProposePotentialNewUserSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/UserManagement/ProposeCreation/ProposePotentialNewUser_OktaDisabled.feature
tests/Nhs.Appointments.Api.Integration/Scenarios/UserManagement/ProposeCreation/ProposePotentialNewUser_OktaEnabled.feature
tests/Nhs.Appointments.Api.Integration/Scenarios/UserManagement/RemoveUserRoleAssignmentsSteps.cs
tests/Nhs.Appointments.Api.Integration/Scenarios/UserManagement/UserManagementBaseFeatureSteps.cs

Un-ignore the OKTA related tests and split into the serial on/off test pattern.
Remove "[Given(@"feature toggle '(.+)' is '(.+)'")]" as we should never be setting this in a test explicilty going forward.

APPT-893 OKTA serial tests wrapper for enabled and disabled.

---

src/client/testing/page-objects/view-availability-appointment-pages/month-view-availability-page.ts
src/client/testing/page-objects/view-availability-appointment-pages/week-view-availability-page.ts
src/client/testing/tests/availability/availability.spec.ts

Refactor so that month and week view tests await each individual iteration by using a for loop instead of forEach.

APPT-XXX Fix flaky view month and view week E2E tests

---

features/prod.feature.flags.json
features/stag.feature.flags.json

Enables the Bulk Import feature flag in both the staging and production environments.

APPT-1011: Enable Bulk Import in both staging and production

---

src/client/testing/tests/availability/availability.spec.ts

We have hard-coded local seed data that is colliding with current increment test, kick the can down the road...

APPT-XXX Update E2E tests to avoid date collisions

---

data/CosmosDbSeeder/items/local/booking_data/20250820.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_33.json
data/CosmosDbSeeder/items/local/booking_data/seed_booking_34.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_33_index.json
data/CosmosDbSeeder/items/local/index_data/seed_booking_34_index.json
src/client/testing/availability.ts
src/client/testing/page-objects/view-availability-appointment-pages/add-services-page.ts
src/client/testing/page-objects/view-availability-appointment-pages/change-availability-page.ts
src/client/testing/page-objects/view-availability-appointment-pages/month-view-availability-page.ts
src/client/testing/page-objects/view-availability-appointment-pages/week-view-availability-page.ts
src/client/testing/tests/availability/availability.spec.ts

Add week availability e2e test to confirm allocation and shuffling behaviour.

APPT-872 Add week availability e2e test

---

src/client/src/app/site/[site]/view-availability/week/edit-session/edit-session-decision.tsx

Update edit session text to include reduce services

APPT-1063 Update edit session text to include reduce services

---

.gitignore
.vscode/tasks.json
data/CsvDataTool/ApiUserDataImportHandler.cs
data/CsvDataTool/ApiUserImportRow.cs
data/CsvDataTool/CsvDataTool.csproj
data/CsvDataTool/CsvProcessor.cs
data/CsvDataTool/ExampleData/sites.csv
data/CsvDataTool/ExampleData/users.csv
data/CsvDataTool/ReportWriter.cs
data/CsvDataTool/SiteDataImportHandler.cs
data/CsvDataTool/SiteMap.cs
data/CsvDataTool/UserDataImportHandler.cs
data/CsvDataTool/UserImportRow.cs
data/CsvDataTool/Validators/ApiUserImportFileValidator.cs
data/CsvDataTool/Validators/ApiUserImportRowValidator.cs
data/CsvDataTool/Validators/CustomValidators.cs
data/CsvDataTool/Validators/SiteDocumentValidator.cs
data/CsvDataTool/Validators/SiteImportFileValidator.cs
data/CsvDataTool/Validators/SiteImportRowValidator.cs
data/CsvDataTool/Validators/UserImportFileValidator.cs
data/CsvDataTool/Validators/UserImportRowValidator.cs
nbs-mya.code-workspace
src/api/Nhs.Appointments.Persistance/Models/SiteDocument.cs
tests/CsvDataTool.UnitTests/CsvProcessorTests.cs
tests/CsvDataTool.UnitTests/SiteImportFileValidatorTests.cs
tests/CsvDataTool.UnitTests/UserImportFileValidatorTests.cs

Adds in some very naïve validation for the Bulk Import tool, before we use it later today. Currently it just checks that each data field is vaguely in the expected format/shape. 
I would have liked to hook this up to the DB and asynchronously check that each user is being added to a site that actually exists, but writing tests for that ended up taking me too long and we need this tool today 🙃 

APPT-1066: Bulk import validation

---

src/client/package-lock.json
src/client/package.json
src/client/src/app/layout.tsx
src/client/src/app/styles/cookie-banner.css
src/client/src/app/styles/custom-nhsuk.scss
src/client/src/app/styles/global.css

Increasing container width to 1100px to allows us to display more content to user.

APPT-983: Increasing container width to 1100px

---

features/int.feature.flags.json
features/prod.feature.flags.json
features/stag.feature.flags.json

APPT-1102: enable okta

---

features/dev.feature.flags.json
features/int.feature.flags.json
features/pen.feature.flags.json
features/prod.feature.flags.json
features/stag.feature.flags.json
src/api/Nhs.Appointments.Api/local.feature.flags.json
src/api/Nhs.Appointments.Core/Features/Flags.cs

Add Feature Flag to enable development of Site Summary Report

APPT-859: add feature flag for site summary report

---

data/CosmosDbSeeder/items/dev/core_data/notification_config.json
data/CosmosDbSeeder/items/int/core_data/notification_config.json

Updating int notification configuration to match dev

APPT-845: Updating notification config for int

---

data/CosmosDbSeeder/items/dev/core_data/notification_config.json
data/CosmosDbSeeder/items/int/core_data/notification_config.json

Updating int notification configuration to match dev
Cherry-picked from https://github.com/NHSDigital/nbs-appointments-management-service/pull/807

APPT-845: Updating notification config for int (#807)

---

data/CosmosDbSeeder/items/dev/core_data/site_ABC01.json
data/CosmosDbSeeder/items/dev/core_data/site_ABC02.json
data/CosmosDbSeeder/items/dev/core_data/site_ABC03.json
data/CosmosDbSeeder/items/local/core_data/site_ABC03.json

Add seed data to new Dev environment

seed site data for dev

---

scripts/pipeline-templates/deploy.yml

APPT-1111 Fix deploy script "not -> ne"

---

src/client/testing/tests/availability/availability.spec.ts

move playwright test forward

---

tests/Nhs.Appointments.Api.Integration/Scenarios/SystemFunctions/RunReminders.feature

Need to ensure tests pass consistently - Skip message bus race condition tests until fixed properly.
Flakiness was introduced by: https://github.com/NHSDigital/nbs-appointments-management-service/commit/5cc21e6e8030a8f4857de8bcbc95c80cd7cbca6e

APPT-XXX Skip message bus race condition tests until fixed properly

---

features/int.feature.flags.json
features/prod.feature.flags.json
features/stag.feature.flags.json

(cherry picked from commit 4924860eee7c452548b0eeaae4f53269ea295057)

APPT-1170 R2.3 Okta re-enabled on Int,Stag,Prod

---

data/CosmosDbSeeder/items/prod/core_data/notification_config.json
data/CosmosDbSeeder/items/stag/core_data/notification_config.json

Updated notification configuration for okta user roles changed event for prod and stag

APPT-1200: Okta user role change notification config update

---

infrastructure/resources/cosmosdb.tf

partition key correction for aggregation container

APPT-1177: partition key correction for aggregation container

---

data/BookingsDataExtracts/BookingsDataExtracts.csproj
data/CosmosDbSeeder/CosmosDbSeeder.csproj
src/api/Nhs.Appointments.Api/Nhs.Appointments.Api.csproj
src/api/Nhs.Appointments.ApiClient/Nhs.Appointments.ApiClient.csproj
src/api/Nhs.Appointments.Core/Nhs.Appointments.Core.csproj

Upgrading Cosmos DB SDK to the latest stable version.

APPT-884: Updating cosmos DB to the latest version

---

src/client/testing/tests/availability/availability.spec.ts

APPT-XXX Skip all availability tests for now

---

tests/Nhs.Appointments.Api.UnitTests/Audit/FunctionMiddlewareTests.cs

APPT-XXX Skip flaky audit unit test

---

src/client/src/app/login/log-in-button.tsx

APPT-1277 Make login button a wrapped link rather than form action

---

data/CosmosDbSeeder/items/dev/core_data/global_roles.json
data/CosmosDbSeeder/items/int/core_data/global_roles.json
data/CosmosDbSeeder/items/local/core_data/global_roles.json
data/CosmosDbSeeder/items/pen/core_data/global_roles.json
data/CosmosDbSeeder/items/perf/core_data/global_roles.json
data/CosmosDbSeeder/items/prod/core_data/global_roles.json
data/CosmosDbSeeder/items/stag/core_data/global_roles.json
src/api/Nhs.Appointments.Api/Auth/PermissionChecker.cs
src/api/Nhs.Appointments.Core/ISiteStore.cs
src/api/Nhs.Appointments.Core/SiteService.cs
src/api/Nhs.Appointments.Persistance/SiteStore.cs
tests/Nhs.Appointments.Api.UnitTests/Auth/PermissionCheckerTests.cs

Adding a new ICB scoped role with required permissions

Appt 834 - Add new ICB scoped role

---

src/client/src/app/login/page.tsx

APPT-1277 Fix login button link styling

---

nbs-mya.code-workspace

Just some VS Code packages I find useful

APPT-XXX: add some packages to make our lives easier

---

infrastructure/environments/dev/main.tf
infrastructure/environments/dev/variables.tf
infrastructure/environments/int/main.tf
infrastructure/environments/int/variables.tf
infrastructure/environments/pen/main.tf
infrastructure/environments/pen/variables.tf
infrastructure/environments/perf-ukw/main.tf
infrastructure/environments/perf-ukw/variables.tf
infrastructure/environments/perf/main.tf
infrastructure/environments/perf/variables.tf
infrastructure/environments/prod-ukw/main.tf
infrastructure/environments/prod-ukw/variables.tf
infrastructure/environments/prod/main.tf
infrastructure/environments/prod/variables.tf
infrastructure/environments/stag-ukw/main.tf
infrastructure/environments/stag-ukw/variables.tf
infrastructure/environments/stag/main.tf
infrastructure/environments/stag/variables.tf

APPT-1322: correct infra vars for gov notify
